$axure.loadCurrentPage({
  "url":"air_s.html",
  "generationDate":new Date(1401111431263.59),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"cc0a0af715de41fa95fea710a3eacff5",
    "type":"Axure:Page",
    "name":"Air s",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3327c8935184a4d88deec3a9880288d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":830},
            "size":{
              "width":540,
              "height":304},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732a553033bf4a4abe57256d7dc31510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":830},
                "size":{
                  "width":540,
                  "height":304},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u0.png"}},
{
          "id":"1f66c58392b545789a8d4c14b9e91722",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":540,
              "height":760},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68ae95538e5e4a519852ecdee412cb88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":540,
                  "height":760},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_post/u14.png"}},
{
          "id":"6a1d0269e9114a948739214bc3d547d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":207,
              "y":35},
            "size":{
              "width":241,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a516bf1bcb9d46b4917bbff8cb82ea1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":207,
                  "y":35},
                "size":{
                  "width":241,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a2554b3aa14d88a498275ab38fdae2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":77},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_post/u4_line.png"}},
{
          "id":"1f6f3e12b447495ea556c3ffd320cf34",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":715},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a4cf048f2858480397ea0ede264b5ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":63,
              "y":130},
            "size":{
              "width":146,
              "height":396}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4205484809344fcbb7d86b562d1febe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":63,
                  "y":130},
                "size":{
                  "width":146,
                  "height":396}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b7490c8c5214ebfb59f8ae2929e8982",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"接机时候的称呼"},
{
          "id":"76c58d3f8a934293b02e6f9d306149e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":211},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"fec56ace4cd8429fa4b20472fe345497",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":174},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"2996354cedf44b8091e5d587c6424029",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":246},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"877f3a379b1c41fcacd88342afe336fd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":281},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"134a7588ce424c21b6e8e8cc80115a17",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":356},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"唯一联系方式 请确保填写正确"},
{
          "id":"7a619fa6fcb94d88a30093cb7ab834ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":499},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d5b09aa8ec4b9b8c0aa5ea69982a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":499},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"ab8d109e94af4ada8d2bf3ad9b1078c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":499},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02b48a13ee5847f9bade1fb038ee15bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":499},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"ffe7e2f48149482faca569241dd10710",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":337,
              "y":499},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7ae9eab11945278c810ca123abd596",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":337,
                  "y":499},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"2fc4f96d230d4e01aad1e1a900038f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":110,
              "y":581},
            "size":{
              "width":400,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa2866cf6c0b49a8855ccadd7cd87e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":110,
                  "y":581},
                "size":{
                  "width":400,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u22.png"}},
{
          "id":"1e71179b01ed4e3ead0e83030523c567",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":130,
              "y":611},
            "size":{
              "width":360,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b934e2a950e4f808643761417a620af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":130,
                  "y":611},
                "size":{
                  "width":360,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a34e6cc095a4967a59ba34de21e23d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":250,
              "y":464},
            "size":{
              "width":40,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ddd77d5244c468a961674c330473f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":250,
                  "y":464},
                "size":{
                  "width":40,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cab3a96aa1843dab16ebd7f942ed92b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":316},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"0da14ec2830342f5b16e752548bdafa0",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":391},
            "size":{
              "width":200,
              "height":63}},
          "adaptiveStyles":{
},
          "placeholderText":"例子：两个大行李箱，一个包裹"},
{
          "id":"c6186722e3f9436b8b15af7dfa1044d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":938},
            "size":{
              "width":235,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754401d351ff4b40b943c5ea76d7436f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":938},
                "size":{
                  "width":235,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b49d87040a1848768bcd60d748a7e071",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":544},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6db0597fae2f407bb8283c0f3f9db253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":544},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"70400c80b2034b2286d46dfbd3409e4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":929},
            "size":{
              "width":94,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e2821f1cb7426893f391eb7c1f77a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":929},
                "size":{
                  "width":94,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u142.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a3327c8935184a4d88deec3a9880288d":{
      "scriptId":"u0"},
    "732a553033bf4a4abe57256d7dc31510":{
      "scriptId":"u1"},
    "1f66c58392b545789a8d4c14b9e91722":{
      "scriptId":"u2"},
    "68ae95538e5e4a519852ecdee412cb88":{
      "scriptId":"u3"},
    "6a1d0269e9114a948739214bc3d547d8":{
      "scriptId":"u4"},
    "a516bf1bcb9d46b4917bbff8cb82ea1c":{
      "scriptId":"u5"},
    "01a2554b3aa14d88a498275ab38fdae2":{
      "scriptId":"u6"},
    "1f6f3e12b447495ea556c3ffd320cf34":{
      "scriptId":"u7"},
    "a4cf048f2858480397ea0ede264b5ddf":{
      "scriptId":"u8"},
    "c4205484809344fcbb7d86b562d1febe":{
      "scriptId":"u9"},
    "1b7490c8c5214ebfb59f8ae2929e8982":{
      "scriptId":"u10"},
    "76c58d3f8a934293b02e6f9d306149e7":{
      "scriptId":"u11"},
    "fec56ace4cd8429fa4b20472fe345497":{
      "scriptId":"u12"},
    "2996354cedf44b8091e5d587c6424029":{
      "scriptId":"u13"},
    "877f3a379b1c41fcacd88342afe336fd":{
      "scriptId":"u14"},
    "134a7588ce424c21b6e8e8cc80115a17":{
      "scriptId":"u15"},
    "7a619fa6fcb94d88a30093cb7ab834ad":{
      "scriptId":"u16"},
    "17d5b09aa8ec4b9b8c0aa5ea69982a2b":{
      "scriptId":"u17"},
    "ab8d109e94af4ada8d2bf3ad9b1078c3":{
      "scriptId":"u18"},
    "02b48a13ee5847f9bade1fb038ee15bc":{
      "scriptId":"u19"},
    "ffe7e2f48149482faca569241dd10710":{
      "scriptId":"u20"},
    "ec7ae9eab11945278c810ca123abd596":{
      "scriptId":"u21"},
    "2fc4f96d230d4e01aad1e1a900038f58":{
      "scriptId":"u22"},
    "aa2866cf6c0b49a8855ccadd7cd87e7d":{
      "scriptId":"u23"},
    "1e71179b01ed4e3ead0e83030523c567":{
      "scriptId":"u24"},
    "7b934e2a950e4f808643761417a620af":{
      "scriptId":"u25"},
    "6a34e6cc095a4967a59ba34de21e23d2":{
      "scriptId":"u26"},
    "9ddd77d5244c468a961674c330473f41":{
      "scriptId":"u27"},
    "4cab3a96aa1843dab16ebd7f942ed92b":{
      "scriptId":"u28"},
    "0da14ec2830342f5b16e752548bdafa0":{
      "scriptId":"u29"},
    "c6186722e3f9436b8b15af7dfa1044d2":{
      "scriptId":"u30"},
    "754401d351ff4b40b943c5ea76d7436f":{
      "scriptId":"u31"},
    "b49d87040a1848768bcd60d748a7e071":{
      "scriptId":"u32"},
    "6db0597fae2f407bb8283c0f3f9db253":{
      "scriptId":"u33"},
    "70400c80b2034b2286d46dfbd3409e4b":{
      "scriptId":"u34"},
    "47e2821f1cb7426893f391eb7c1f77a4":{
      "scriptId":"u35"}}});