$axure.loadCurrentPage({
  "url":"fast_channel.html",
  "generationDate":new Date(1399385438277.93),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"75fdd985fe0045be844f96f4d9c09486",
    "type":"Axure:Page",
    "name":"Fast channel",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18a1141fc57b41c4b1ee2fc4eb8628fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":540,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"970b40ee79ca4f1cbfe270c626cd4ac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":540,
                  "height":890},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u0.png"}},
{
          "id":"a40327f1f00a4ac48edf9bf62e54410f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":184,
              "y":30},
            "size":{
              "width":212,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e02c4f1f5424123bd9c4502ad09ee8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":184,
                  "y":30},
                "size":{
                  "width":212,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6282e28274a944f1a9859ed6cf897e07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":77},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_post/u4_line.png"}},
{
          "id":"2dd004115a2948c68e2bc95600c747eb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":790},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b4ad1078d27b4a729d176492d4c001e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":82,
              "y":130},
            "size":{
              "width":127,
              "height":468}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cdbcead52cd473d8604d38cf2a5c63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":82,
                  "y":130},
                "size":{
                  "width":127,
                  "height":468}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff9cb9e719264981ac92d14bd616c032",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"称呼"},
{
          "id":"7ddbbdf602d14ae3859b422b4e06a61d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":211},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"主要联系方式 请确保填写正确"},
{
          "id":"d1fa8959c8fa41979914da2f10ac303a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":174},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"重要联系方式 请确保填写正确"},
{
          "id":"3431513e984741a1944ffab645d82cff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":246},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"ea967da9b1cd4589a75551d93ab5cca7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":281},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"c3a08dca4876435da03596c963a4564a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":316},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"1a3d89f900c5410ab686c5ec96ab00aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":260,
              "y":508},
            "size":{
              "width":190,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f621eff7fb994e83b879e207b4e4e7ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":260,
                  "y":508},
                "size":{
                  "width":190,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u14.png"}},
{
          "id":"17b9a474a2e24675af9da71396142c7e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":250,
              "y":504},
            "size":{
              "width":14,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9770a9222ca24625a82c963c0719dec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":250,
                  "y":504},
                "size":{
                  "width":14,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u16.png"}},
{
          "id":"8a38d15dc5a94882b146aadf0412fd7c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":442,
              "y":504},
            "size":{
              "width":14,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ad6669de7045c0a89040df94143b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":442,
                  "y":504},
                "size":{
                  "width":14,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u16.png"}},
{
          "id":"dd1606f07d5547efb13ba248cfe80255",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":533},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ce75c10ebd44152879fa74fe772c635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":533},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u20.png"}},
{
          "id":"e029ebc917ed43c3b8e56bbbe932dfda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":533},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a42a1a6fd843cb9c01a6db8a2f492c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":533},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u20.png"}},
{
          "id":"230ca12adf874c6c87f0afbde8e3cc7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":543},
            "size":{
              "width":30,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/fast_channel/u24_line.png"}},
{
          "id":"2a4794ba871e4c9686cfdb88be1cdc44",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":573},
            "size":{
              "width":200,
              "height":81}},
          "adaptiveStyles":{
}},
{
          "id":"69e579841f3b42e29f5045894dfaa17f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":50},
            "size":{
              "width":280,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebead2203d6b42bd8b15a22566c7ab73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":50},
                "size":{
                  "width":280,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cbf6ca7d88a449398acbc6e490fcb77",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":710},
            "size":{
              "width":205,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8316f8b7ecfd4f069e933b87010020cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":215,
                  "y":710},
                "size":{
                  "width":205,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"901d6a1cf127407185c8d2f0b21b345e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":355},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"逗号隔开"},
{
          "id":"b2bb6f5f868f4147a265f4e292d615df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":389},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"逗号隔开"},
{
          "id":"2f589ed3607a42a591490355c1f46857",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":429},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb51f3471b0432da6fbc74179673532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":429},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0ea246f59783483c9918a207e442b386",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":429},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa06a1f510044200abbb2ba51b3d027c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":429},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8768470a50ae4b718fe662352de7e8a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":250,
              "y":461},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"817bb54fe0614fb6ba9b8fca5e133b70",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":435},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/fast_channel/u37_line.png"}},
{
          "id":"448fded40794445c88f47ab140513f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":673,
              "y":407},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03be60d8e73041cab6f80b9fb275ce00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":673,
                  "y":407},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bedcf2886e9347f3a5a0686c9e25114b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":673,
              "y":433},
            "size":{
              "width":47,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d58811a3f3da46bf927728a5d414da9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":438},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0153ec22fa4b5fab2cfd8df296a638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":438},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94819e58001d472aab60a6e9be68bb05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1040},
            "size":{
              "width":540,
              "height":420},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eadc63ad82f24c05a76f902197ccca67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1040},
                "size":{
                  "width":540,
                  "height":420},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fast_channel/u43.png"}},
{
          "id":"fdd07bbb0f854e82b8b92bab0fc3564a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":1270},
            "size":{
              "width":222,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a1b473558504d0d8a7615f05f47a713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":1270},
                "size":{
                  "width":222,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff8da11618794220819f14efa40c46f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":182,
              "y":1188},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7528858ac28e4883bfa55fb6b9e73550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":182,
                  "y":1188},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880c0cd3f1ce4ad4b29d5ad20ce06b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":182,
              "y":1220},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8e831d166734d2f80f5fbb99e1c0f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":182,
                  "y":1220},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47f5a600e1ae4eb7b111c82e3ee4926f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":1180},
            "size":{
              "width":94,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124017b165b14e198478c9177f719d9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":1180},
                "size":{
                  "width":94,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u142.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "18a1141fc57b41c4b1ee2fc4eb8628fb":{
      "scriptId":"u0"},
    "970b40ee79ca4f1cbfe270c626cd4ac0":{
      "scriptId":"u1"},
    "a40327f1f00a4ac48edf9bf62e54410f":{
      "scriptId":"u2"},
    "9e02c4f1f5424123bd9c4502ad09ee8b":{
      "scriptId":"u3"},
    "6282e28274a944f1a9859ed6cf897e07":{
      "scriptId":"u4"},
    "2dd004115a2948c68e2bc95600c747eb":{
      "scriptId":"u5"},
    "b4ad1078d27b4a729d176492d4c001e4":{
      "scriptId":"u6"},
    "5cdbcead52cd473d8604d38cf2a5c63c":{
      "scriptId":"u7"},
    "ff9cb9e719264981ac92d14bd616c032":{
      "scriptId":"u8"},
    "7ddbbdf602d14ae3859b422b4e06a61d":{
      "scriptId":"u9"},
    "d1fa8959c8fa41979914da2f10ac303a":{
      "scriptId":"u10"},
    "3431513e984741a1944ffab645d82cff":{
      "scriptId":"u11"},
    "ea967da9b1cd4589a75551d93ab5cca7":{
      "scriptId":"u12"},
    "c3a08dca4876435da03596c963a4564a":{
      "scriptId":"u13"},
    "1a3d89f900c5410ab686c5ec96ab00aa":{
      "scriptId":"u14"},
    "f621eff7fb994e83b879e207b4e4e7ec":{
      "scriptId":"u15"},
    "17b9a474a2e24675af9da71396142c7e":{
      "scriptId":"u16"},
    "9770a9222ca24625a82c963c0719dec5":{
      "scriptId":"u17"},
    "8a38d15dc5a94882b146aadf0412fd7c":{
      "scriptId":"u18"},
    "b4ad6669de7045c0a89040df94143b35":{
      "scriptId":"u19"},
    "dd1606f07d5547efb13ba248cfe80255":{
      "scriptId":"u20"},
    "1ce75c10ebd44152879fa74fe772c635":{
      "scriptId":"u21"},
    "e029ebc917ed43c3b8e56bbbe932dfda":{
      "scriptId":"u22"},
    "f4a42a1a6fd843cb9c01a6db8a2f492c":{
      "scriptId":"u23"},
    "230ca12adf874c6c87f0afbde8e3cc7e":{
      "scriptId":"u24"},
    "2a4794ba871e4c9686cfdb88be1cdc44":{
      "scriptId":"u25"},
    "69e579841f3b42e29f5045894dfaa17f":{
      "scriptId":"u26"},
    "ebead2203d6b42bd8b15a22566c7ab73":{
      "scriptId":"u27"},
    "7cbf6ca7d88a449398acbc6e490fcb77":{
      "scriptId":"u28"},
    "8316f8b7ecfd4f069e933b87010020cc":{
      "scriptId":"u29"},
    "901d6a1cf127407185c8d2f0b21b345e":{
      "scriptId":"u30"},
    "b2bb6f5f868f4147a265f4e292d615df":{
      "scriptId":"u31"},
    "2f589ed3607a42a591490355c1f46857":{
      "scriptId":"u32"},
    "acb51f3471b0432da6fbc74179673532":{
      "scriptId":"u33"},
    "0ea246f59783483c9918a207e442b386":{
      "scriptId":"u34"},
    "fa06a1f510044200abbb2ba51b3d027c":{
      "scriptId":"u35"},
    "8768470a50ae4b718fe662352de7e8a0":{
      "scriptId":"u36"},
    "817bb54fe0614fb6ba9b8fca5e133b70":{
      "scriptId":"u37"},
    "448fded40794445c88f47ab140513f0f":{
      "scriptId":"u38"},
    "03be60d8e73041cab6f80b9fb275ce00":{
      "scriptId":"u39"},
    "bedcf2886e9347f3a5a0686c9e25114b":{
      "scriptId":"u40"},
    "d58811a3f3da46bf927728a5d414da9d":{
      "scriptId":"u41"},
    "dc0153ec22fa4b5fab2cfd8df296a638":{
      "scriptId":"u42"},
    "94819e58001d472aab60a6e9be68bb05":{
      "scriptId":"u43"},
    "eadc63ad82f24c05a76f902197ccca67":{
      "scriptId":"u44"},
    "fdd07bbb0f854e82b8b92bab0fc3564a":{
      "scriptId":"u45"},
    "0a1b473558504d0d8a7615f05f47a713":{
      "scriptId":"u46"},
    "ff8da11618794220819f14efa40c46f3":{
      "scriptId":"u47"},
    "7528858ac28e4883bfa55fb6b9e73550":{
      "scriptId":"u48"},
    "880c0cd3f1ce4ad4b29d5ad20ce06b8f":{
      "scriptId":"u49"},
    "b8e831d166734d2f80f5fbb99e1c0f02":{
      "scriptId":"u50"},
    "47f5a600e1ae4eb7b111c82e3ee4926f":{
      "scriptId":"u51"},
    "124017b165b14e198478c9177f719d9e":{
      "scriptId":"u52"}}});