$axure.loadCurrentPage({
  "url":"nolist.html",
  "generationDate":new Date(1397918780308.92),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"36809d9a900e475c9189231f09fd0c55",
    "type":"Axure:Page",
    "name":"NoList",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});