$axure.loadCurrentPage({
  "url":"nolist.html",
  "generationDate":new Date(1399126231555.18),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"36809d9a900e475c9189231f09fd0c55",
    "type":"Axure:Page",
    "name":"NoList",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b3f8b1dbdef432799779379d75c7372",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":60},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71f708c02f24fb5ade949eeaec57c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":60},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u2.png"}},
{
          "id":"fca20cb098374158948daf6d46a50bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":10,
              "y":2},
            "size":{
              "width":149,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fedb3464a7134593b091122f2ede0a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":10,
                  "y":2},
                "size":{
                  "width":149,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c24475827d34a43be225986a2cf8004",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":830,
              "y":19},
            "size":{
              "width":70,
              "height":24},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be013f835a0145c7bb59693be53ee3e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":830,
                  "y":19},
                "size":{
                  "width":70,
                  "height":24},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u6.png"}},
{
          "id":"c25a8bb5c2b749bba8ec5f505773c18e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF825C},
            "location":{
              "x":800,
              "y":23},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad43d87f7cd4c42ab3186abad7915e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF825C},
                "location":{
                  "x":800,
                  "y":23},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account/u250.png"}},
{
          "id":"19a91d0dc7974b92a065b7e768e47a7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":930,
              "y":23},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abfcaf18642a4569980fad4a1baa32eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":930,
                  "y":23},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account/u252.png"}},
{
          "id":"c72feb9006a4464b9acc745e45541cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1000,
              "height":1320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011a950808574a96a3be38f2d0f5211d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1000,
                  "height":1320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/nolist/u10.png"}},
{
          "id":"114b1fc9e04346748e837dddfba59bd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":133},
            "size":{
              "width":374,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f34807d573f941769828ac8761ce6db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":133},
                "size":{
                  "width":374,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35ad0d22ccc343b09fe874ba65141d9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":322,
              "y":200},
            "size":{
              "width":271,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"422de85650144a2bb392cc70753c6f87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":322,
                  "y":200},
                "size":{
                  "width":271,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ba24bfdc5314132b92869f7a4127723",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":321,
              "y":270},
            "size":{
              "width":217,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886582f00b624414ad345334e910fa23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":321,
                  "y":270},
                "size":{
                  "width":217,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdf4b2ee054b4140a3b2a407535a2744",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":551},
            "size":{
              "width":300,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436a2916add24f1e8164dd95d96ddba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":551},
                "size":{
                  "width":300,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ab59cc094834a0bb2e719d4a41de9db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":551},
            "size":{
              "width":300,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520ca7af47a94f50802c0be32ad386bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":551},
                "size":{
                  "width":300,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a64ea9abb3e40869a51f0cecaf2406f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":876},
            "size":{
              "width":300,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e4fb9d766a45be9907137841ad884b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":876},
                "size":{
                  "width":300,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c202ff318e424ea4b04d397c50967471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":876},
            "size":{
              "width":300,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cfc5404edfb4737af08a9d9a05c296a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":876},
                "size":{
                  "width":300,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"462359a2a17e4c42a6474d947b166214",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":676,
              "y":370},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d1f0debdbc042d1840b53f5a305bc2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":676,
                  "y":370},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8874f160c5e04763aeaf219422249866",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":391},
            "size":{
              "width":300,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5bb1b70009540218ce54e80283f07b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":391},
                "size":{
                  "width":300,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc9b3b29543c4035aaba6c44e8f2e62a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":408},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942f35a861b340359b4b85c3bdda1420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":408},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d9af4deec6e41b5aeb202000eb3fee8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":320}},
          "adaptiveStyles":{
},
          "masterId":"910632d876054e9daba5e1ff1427cf71"}]}},
  "masters":{
    "910632d876054e9daba5e1ff1427cf71":{
      "packageId":"910632d876054e9daba5e1ff1427cf71",
      "type":"Axure:Master",
      "name":"search",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"90ed9246fe554982af88c3bf9d3428b7",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "stateStyles":{
                "hint":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1}}},
              "size":{
                "width":720,
                "height":45}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onTextChange":{
                "description":"OnTextChange",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 渐进提示 淡入淡出 300 毫秒",
                        "objectsToFades":[{
                            "objectPath":["f60087697af14281a617c88104cf67de"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"fade",
                                "duration":300,
                                "showType":"none"}}}]}]}]},
              "onLostFocus":{
                "description":"OnLostFocus",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 渐进提示 淡入淡出 300 毫秒",
                        "objectsToFades":[{
                            "objectPath":["f60087697af14281a617c88104cf67de"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"fade",
                                "duration":300,
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "placeholderText":"tell me your school , I will find new house for you !!"},
{
            "id":"ee1dc63a43dd419e81f512517205750b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":610,
                "y":10},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"f60087697af14281a617c88104cf67de",
            "label":"渐进提示",
            "type":"listBox",
            "styleType":"listBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":45},
              "size":{
                "width":500,
                "height":100},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onFocus":{
                "description":"OnFocus",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 search list",
                        "target":{
                          "targetType":"page",
                          "url":"search_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"df85b2b91a494b7ca5b94ef47e1bd92e",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":500,
                "y":13},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "1b3f8b1dbdef432799779379d75c7372":{
      "scriptId":"u0"},
    "d71f708c02f24fb5ade949eeaec57c22":{
      "scriptId":"u1"},
    "fca20cb098374158948daf6d46a50bc1":{
      "scriptId":"u2"},
    "fedb3464a7134593b091122f2ede0a52":{
      "scriptId":"u3"},
    "9c24475827d34a43be225986a2cf8004":{
      "scriptId":"u4"},
    "be013f835a0145c7bb59693be53ee3e7":{
      "scriptId":"u5"},
    "c25a8bb5c2b749bba8ec5f505773c18e":{
      "scriptId":"u6"},
    "4ad43d87f7cd4c42ab3186abad7915e9":{
      "scriptId":"u7"},
    "19a91d0dc7974b92a065b7e768e47a7e":{
      "scriptId":"u8"},
    "abfcaf18642a4569980fad4a1baa32eb":{
      "scriptId":"u9"},
    "c72feb9006a4464b9acc745e45541cfd":{
      "scriptId":"u10"},
    "011a950808574a96a3be38f2d0f5211d":{
      "scriptId":"u11"},
    "114b1fc9e04346748e837dddfba59bd2":{
      "scriptId":"u12"},
    "f34807d573f941769828ac8761ce6db9":{
      "scriptId":"u13"},
    "35ad0d22ccc343b09fe874ba65141d9e":{
      "scriptId":"u14"},
    "422de85650144a2bb392cc70753c6f87":{
      "scriptId":"u15"},
    "6ba24bfdc5314132b92869f7a4127723":{
      "scriptId":"u16"},
    "886582f00b624414ad345334e910fa23":{
      "scriptId":"u17"},
    "fdf4b2ee054b4140a3b2a407535a2744":{
      "scriptId":"u18"},
    "436a2916add24f1e8164dd95d96ddba2":{
      "scriptId":"u19"},
    "4ab59cc094834a0bb2e719d4a41de9db":{
      "scriptId":"u20"},
    "520ca7af47a94f50802c0be32ad386bb":{
      "scriptId":"u21"},
    "6a64ea9abb3e40869a51f0cecaf2406f":{
      "scriptId":"u22"},
    "d5e4fb9d766a45be9907137841ad884b":{
      "scriptId":"u23"},
    "c202ff318e424ea4b04d397c50967471":{
      "scriptId":"u24"},
    "7cfc5404edfb4737af08a9d9a05c296a":{
      "scriptId":"u25"},
    "462359a2a17e4c42a6474d947b166214":{
      "scriptId":"u26"},
    "7d1f0debdbc042d1840b53f5a305bc2b":{
      "scriptId":"u27"},
    "8874f160c5e04763aeaf219422249866":{
      "scriptId":"u28"},
    "b5bb1b70009540218ce54e80283f07b1":{
      "scriptId":"u29"},
    "cc9b3b29543c4035aaba6c44e8f2e62a":{
      "scriptId":"u30"},
    "942f35a861b340359b4b85c3bdda1420":{
      "scriptId":"u31"},
    "5d9af4deec6e41b5aeb202000eb3fee8":{
      "scriptId":"u32",
      "90ed9246fe554982af88c3bf9d3428b7":{
        "scriptId":"u33"},
      "ee1dc63a43dd419e81f512517205750b":{
        "scriptId":"u34"},
      "f60087697af14281a617c88104cf67de":{
        "scriptId":"u35"},
      "df85b2b91a494b7ca5b94ef47e1bd92e":{
        "scriptId":"u36"}}}});