$axure.loadCurrentPage({
  "url":"t-mobile.html",
  "generationDate":new Date(1400676673872.43),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"a3530f5b87da4b2485b81dbf38613433",
    "type":"Axure:Page",
    "name":"T-Mobile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f4603dbdacf04a8ab3585eb1bbde6b0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":700,
              "height":1110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2595720aa570403b98603987ce1e6e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":700,
                  "height":1110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t-mobile/u0.png"}},
{
          "id":"a16145cf87364fceb296aa7ce0a5e0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":62,
              "y":120},
            "size":{
              "width":608,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d7469da9734231a94d73d72f53cf6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":62,
                  "y":120},
                "size":{
                  "width":608,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b356d98843a4fbe96d4829ad0fd64aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":39},
            "size":{
              "width":308,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d37dc5cb8f314f948cbec3c5174874a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":39},
                "size":{
                  "width":308,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t-mobile/u4.png"}},
{
          "id":"1a0a4b2135494eb9b0910b5bca8b8d31",
          "label":"套餐",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":220},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"27c478010c9d476d87ecd415280b8b94",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4e542b09506a4c1193428ac8aec2d1aa",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"menuObject",
                  "styleType":"menuObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":517,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ee705a8ff6743b59930e8acbd031b5f",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"table",
                      "styleType":"table",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":517,
                          "height":49}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"72d1cb997a5342429525734215e84b5f",
                          "label":"",
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"tableCell",
                          "styleType":"tableCell",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "underline":true,
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "stateStyles":{
                              "mouseOver":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":279,
                              "height":49},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5ba2f85f9cd34886b2e5dd96297ffaa9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "underline":true,
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "stateStyles":{
                                  "mouseOver":{
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFFFFFFFF,
                                      "opacity":1},
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFFFF9900}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":279,
                                  "height":49},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "mouseOver~":"images/t-mobile/u9_mouseOver.png"}},
{
                          "id":"e92b8854d9e84674883e30cc5f014fe5",
                          "label":"",
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"tableCell",
                          "styleType":"tableCell",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "stateStyles":{
                              "mouseOver":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":279,
                              "y":0},
                            "size":{
                              "width":238,
                              "height":49},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"42275eeb1d784754b2c401efe6eb4ac2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "stateStyles":{
                                  "mouseOver":{
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFFFFFFFF,
                                      "opacity":1},
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFFFF9900}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":279,
                                  "y":0},
                                "size":{
                                  "width":238,
                                  "height":49},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 套餐 to 状态2",
                                      "panelsToStates":[{
                                          "panelPath":["1a0a4b2135494eb9b0910b5bca8b8d31"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "mouseOver~":"images/t-mobile/u11_mouseOver.png"}}]}]},
{
                  "id":"7562eb56155b4346ae8df5daf0e71a8d",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":49},
                    "size":{
                      "width":517,
                      "height":420}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b492fb01db6a4af3aaaf9e88b60c9e48",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b056b683cfe54e9790865228be8ee351",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"ae872145302548379190a1d83cb51fd5",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":84},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a14a784eb1514622bed17fd0e90b7bba",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":84},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"0e6c6007ef024b359170f8cb3b43560c",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":336},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a73e46383aa641b5b9cf78922f546cec",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":336},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u30.png"}},
{
                      "id":"a11f54690d724da28edb71323a4050a1",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":0},
                        "size":{
                          "width":259,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fc1d754929054e8f9cd61f8becb6fc82",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":0},
                            "size":{
                              "width":259,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u16.png"}},
{
                      "id":"8f9c81a2a10c4354b8318ba7ee510981",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":84},
                        "size":{
                          "width":259,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2013b88e7c0f4e46a2c6e9de0b05e21c",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":84},
                            "size":{
                              "width":259,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u16.png"}},
{
                      "id":"8d8d8de6713147a7885c72c8bcc2feb8",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":336},
                        "size":{
                          "width":259,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d356424bd64e4b77be0aa7c56cfcc655",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":336},
                            "size":{
                              "width":259,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u32.png"}},
{
                      "id":"528641c4b16e4f73b0f33e5c87d27202",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":168},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f4d3bd0a6c3a42a8bf53dd3de30f81e1",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":168},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"ab7ab59bd05949f78c5b88f10e9085f5",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":168},
                        "size":{
                          "width":259,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ba3a5260f89340738780e7d9ceeb1be5",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":168},
                            "size":{
                              "width":259,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u16.png"}},
{
                      "id":"d80e52744fec41e8a859929545e4d4d8",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":252},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"489c512dbf8d40b8b9af366a073e96c1",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":252},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"974dcb3b863549429d7c6b58b2e2afee",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":252},
                        "size":{
                          "width":259,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c4e7b0ae09c844c6accc9e4d207ac74f",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":252},
                            "size":{
                              "width":259,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u16.png"}}]},
{
                  "id":"8aba28fe23c34393a1eb2e232275c4de",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":492},
                    "size":{
                      "width":517,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88b9c56ed3a04887b5904d22a473a2c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":492},
                        "size":{
                          "width":517,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"0950f01fcce14f4bbb7ebc448cd61fa8",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e3fc87f05d1d4dd09eeb4264aff31b88",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"menuObject",
                  "styleType":"menuObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":517,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebbdcdbc43fa44bd8e509d0fd51b53c9",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"table",
                      "styleType":"table",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":517,
                          "height":49}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9e5c42f50aa148c09c7c1191c95d91db",
                          "label":"",
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"tableCell",
                          "styleType":"tableCell",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "stateStyles":{
                              "mouseOver":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":259,
                              "height":49},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"eea5c0762df144f49ebb4c61b388ad4a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "stateStyles":{
                                  "mouseOver":{
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFFFFFFFF,
                                      "opacity":1},
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFFFF9900}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":259,
                                  "height":49},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 套餐 to 状态1",
                                      "panelsToStates":[{
                                          "panelPath":["1a0a4b2135494eb9b0910b5bca8b8d31"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "mouseOver~":"images/t-mobile/u38_mouseOver.png"}},
{
                          "id":"7667f22363fa4f1991ef943bfd0a096f",
                          "label":"",
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"tableCell",
                          "styleType":"tableCell",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "underline":true,
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "stateStyles":{
                              "mouseOver":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900}}},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":259,
                              "y":0},
                            "size":{
                              "width":258,
                              "height":49},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"11072d6ba5734ced9f6ff5ab278edf29",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "underline":true,
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "stateStyles":{
                                  "mouseOver":{
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFFFFFFFF,
                                      "opacity":1},
                                    "fill":{
                                      "fillType":"solid",
                                      "color":0xFFFF9900}}},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":259,
                                  "y":0},
                                "size":{
                                  "width":258,
                                  "height":49},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "mouseOver~":"images/t-mobile/u40_mouseOver.png"}}]}]},
{
                  "id":"ba5d732e7c244335b513fcf7562f826e",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":49},
                    "size":{
                      "width":514,
                      "height":452}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee3bad006d3d48188d7711ddeec69e51",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":258,
                          "height":116},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7cecad229ae04c4d8888e943790f100f",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "size":{
                              "width":258,
                              "height":116},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u43.png"}},
{
                      "id":"430379028b2c4ae19e5bb056ed2e61b8",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":116},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7ea4610ae5d24fae93b624c1e112d392",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":116},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"978777c87b374792b70d17865851e4d0",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":368},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7e652de7ead0414daa9f1865ae79b0cf",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":368},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u30.png"}},
{
                      "id":"10d6d96a4c0f48f082e18363dd429967",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"23acaee711784525a5e2c1e7045ca4dd",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":200},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"37115fb8a8da46b488d159cf19f5939c",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":284},
                        "size":{
                          "width":258,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ef32157eb0364cc48e36d20909e8c864",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":0,
                              "y":284},
                            "size":{
                              "width":258,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u14.png"}},
{
                      "id":"ebd41b2bd97d4cc397f65011c89d6351",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":116},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4a2769f5e17b4387b073080e4c606fda",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":0},
                            "size":{
                              "width":130,
                              "height":116},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u45.png"}},
{
                      "id":"9ef6303e810f41a1983dcb20017bfddc",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":116},
                        "size":{
                          "width":130,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6b08311e1f994b629ee0af353b931383",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":116},
                            "size":{
                              "width":130,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u51.png"}},
{
                      "id":"3bac92026c4c44e6bce8eba684cfe50f",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":200},
                        "size":{
                          "width":130,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"88f23f4eb98245d09c4f325be2db9d99",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":200},
                            "size":{
                              "width":130,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u51.png"}},
{
                      "id":"1f227c16023e4197b4d0ccdbf7081926",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":284},
                        "size":{
                          "width":130,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c9948a8a23664695bb9250adc8b55eeb",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":284},
                            "size":{
                              "width":130,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u51.png"}},
{
                      "id":"77dad75de66949158dc9ba3f1314399f",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":258,
                          "y":368},
                        "size":{
                          "width":130,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"df98d213ab8945878a65671b2173ab7a",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":258,
                              "y":368},
                            "size":{
                              "width":130,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u69.png"}},
{
                      "id":"a59f1c85ad414a7d9ecfe52343d60aab",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":388,
                          "y":0},
                        "size":{
                          "width":126,
                          "height":116},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5850ca6a069249e4a914218aca8e11aa",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":388,
                              "y":0},
                            "size":{
                              "width":126,
                              "height":116},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u47.png"}},
{
                      "id":"3addab0621484b5996e982bfb4d4b911",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":388,
                          "y":116},
                        "size":{
                          "width":126,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"83d6bf9945b5444a89392c1d682c63d8",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":388,
                              "y":116},
                            "size":{
                              "width":126,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u53.png"}},
{
                      "id":"51e48c8530de4f24bb8d44042df7fb1d",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":388,
                          "y":200},
                        "size":{
                          "width":126,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b4b0d68fe6b740fcbeaf8f69614be9b5",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":388,
                              "y":200},
                            "size":{
                              "width":126,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u53.png"}},
{
                      "id":"62439f6481c3489d8ecb30c7e25e27dd",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":388,
                          "y":284},
                        "size":{
                          "width":126,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3b6b67c339894e2ab67c34d4fd4a109b",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":388,
                              "y":284},
                            "size":{
                              "width":126,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u53.png"}},
{
                      "id":"fb73ccaddb824b57922143b0f18f3e42",
                      "label":"",
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":388,
                          "y":368},
                        "size":{
                          "width":126,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE1E1E1}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6f6cf56b4b6c48cb8038da912ce17c8b",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":388,
                              "y":368},
                            "size":{
                              "width":126,
                              "height":84},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE1E1E1}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/t-mobile/u71.png"}}]},
{
                  "id":"f915442532bc4a77a3ec77828e9593d8",
                  "label":"",
                  "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":530},
                    "size":{
                      "width":517,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32d82741d4704e4c830110851a35bf34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a0a4b2135494eb9b0910b5bca8b8d31",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":530},
                        "size":{
                          "width":517,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c1c63ac5720e459d8fafaccf3dc59e98",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1210},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f4603dbdacf04a8ab3585eb1bbde6b0c":{
      "scriptId":"u0"},
    "2595720aa570403b98603987ce1e6e1a":{
      "scriptId":"u1"},
    "a16145cf87364fceb296aa7ce0a5e0e3":{
      "scriptId":"u2"},
    "68d7469da9734231a94d73d72f53cf6d":{
      "scriptId":"u3"},
    "5b356d98843a4fbe96d4829ad0fd64aa":{
      "scriptId":"u4"},
    "d37dc5cb8f314f948cbec3c5174874a7":{
      "scriptId":"u5"},
    "1a0a4b2135494eb9b0910b5bca8b8d31":{
      "scriptId":"u6"},
    "4e542b09506a4c1193428ac8aec2d1aa":{
      "scriptId":"u7"},
    "8ee705a8ff6743b59930e8acbd031b5f":{
      "scriptId":"u8"},
    "72d1cb997a5342429525734215e84b5f":{
      "scriptId":"u9"},
    "5ba2f85f9cd34886b2e5dd96297ffaa9":{
      "scriptId":"u10"},
    "e92b8854d9e84674883e30cc5f014fe5":{
      "scriptId":"u11"},
    "42275eeb1d784754b2c401efe6eb4ac2":{
      "scriptId":"u12"},
    "7562eb56155b4346ae8df5daf0e71a8d":{
      "scriptId":"u13"},
    "b492fb01db6a4af3aaaf9e88b60c9e48":{
      "scriptId":"u14"},
    "b056b683cfe54e9790865228be8ee351":{
      "scriptId":"u15"},
    "a11f54690d724da28edb71323a4050a1":{
      "scriptId":"u16"},
    "fc1d754929054e8f9cd61f8becb6fc82":{
      "scriptId":"u17"},
    "ae872145302548379190a1d83cb51fd5":{
      "scriptId":"u18"},
    "a14a784eb1514622bed17fd0e90b7bba":{
      "scriptId":"u19"},
    "8f9c81a2a10c4354b8318ba7ee510981":{
      "scriptId":"u20"},
    "2013b88e7c0f4e46a2c6e9de0b05e21c":{
      "scriptId":"u21"},
    "528641c4b16e4f73b0f33e5c87d27202":{
      "scriptId":"u22"},
    "f4d3bd0a6c3a42a8bf53dd3de30f81e1":{
      "scriptId":"u23"},
    "ab7ab59bd05949f78c5b88f10e9085f5":{
      "scriptId":"u24"},
    "ba3a5260f89340738780e7d9ceeb1be5":{
      "scriptId":"u25"},
    "d80e52744fec41e8a859929545e4d4d8":{
      "scriptId":"u26"},
    "489c512dbf8d40b8b9af366a073e96c1":{
      "scriptId":"u27"},
    "974dcb3b863549429d7c6b58b2e2afee":{
      "scriptId":"u28"},
    "c4e7b0ae09c844c6accc9e4d207ac74f":{
      "scriptId":"u29"},
    "0e6c6007ef024b359170f8cb3b43560c":{
      "scriptId":"u30"},
    "a73e46383aa641b5b9cf78922f546cec":{
      "scriptId":"u31"},
    "8d8d8de6713147a7885c72c8bcc2feb8":{
      "scriptId":"u32"},
    "d356424bd64e4b77be0aa7c56cfcc655":{
      "scriptId":"u33"},
    "8aba28fe23c34393a1eb2e232275c4de":{
      "scriptId":"u34"},
    "88b9c56ed3a04887b5904d22a473a2c3":{
      "scriptId":"u35"},
    "e3fc87f05d1d4dd09eeb4264aff31b88":{
      "scriptId":"u36"},
    "ebbdcdbc43fa44bd8e509d0fd51b53c9":{
      "scriptId":"u37"},
    "9e5c42f50aa148c09c7c1191c95d91db":{
      "scriptId":"u38"},
    "eea5c0762df144f49ebb4c61b388ad4a":{
      "scriptId":"u39"},
    "7667f22363fa4f1991ef943bfd0a096f":{
      "scriptId":"u40"},
    "11072d6ba5734ced9f6ff5ab278edf29":{
      "scriptId":"u41"},
    "ba5d732e7c244335b513fcf7562f826e":{
      "scriptId":"u42"},
    "ee3bad006d3d48188d7711ddeec69e51":{
      "scriptId":"u43"},
    "7cecad229ae04c4d8888e943790f100f":{
      "scriptId":"u44"},
    "ebd41b2bd97d4cc397f65011c89d6351":{
      "scriptId":"u45"},
    "4a2769f5e17b4387b073080e4c606fda":{
      "scriptId":"u46"},
    "a59f1c85ad414a7d9ecfe52343d60aab":{
      "scriptId":"u47"},
    "5850ca6a069249e4a914218aca8e11aa":{
      "scriptId":"u48"},
    "430379028b2c4ae19e5bb056ed2e61b8":{
      "scriptId":"u49"},
    "7ea4610ae5d24fae93b624c1e112d392":{
      "scriptId":"u50"},
    "9ef6303e810f41a1983dcb20017bfddc":{
      "scriptId":"u51"},
    "6b08311e1f994b629ee0af353b931383":{
      "scriptId":"u52"},
    "3addab0621484b5996e982bfb4d4b911":{
      "scriptId":"u53"},
    "83d6bf9945b5444a89392c1d682c63d8":{
      "scriptId":"u54"},
    "10d6d96a4c0f48f082e18363dd429967":{
      "scriptId":"u55"},
    "23acaee711784525a5e2c1e7045ca4dd":{
      "scriptId":"u56"},
    "3bac92026c4c44e6bce8eba684cfe50f":{
      "scriptId":"u57"},
    "88f23f4eb98245d09c4f325be2db9d99":{
      "scriptId":"u58"},
    "51e48c8530de4f24bb8d44042df7fb1d":{
      "scriptId":"u59"},
    "b4b0d68fe6b740fcbeaf8f69614be9b5":{
      "scriptId":"u60"},
    "37115fb8a8da46b488d159cf19f5939c":{
      "scriptId":"u61"},
    "ef32157eb0364cc48e36d20909e8c864":{
      "scriptId":"u62"},
    "1f227c16023e4197b4d0ccdbf7081926":{
      "scriptId":"u63"},
    "c9948a8a23664695bb9250adc8b55eeb":{
      "scriptId":"u64"},
    "62439f6481c3489d8ecb30c7e25e27dd":{
      "scriptId":"u65"},
    "3b6b67c339894e2ab67c34d4fd4a109b":{
      "scriptId":"u66"},
    "978777c87b374792b70d17865851e4d0":{
      "scriptId":"u67"},
    "7e652de7ead0414daa9f1865ae79b0cf":{
      "scriptId":"u68"},
    "77dad75de66949158dc9ba3f1314399f":{
      "scriptId":"u69"},
    "df98d213ab8945878a65671b2173ab7a":{
      "scriptId":"u70"},
    "fb73ccaddb824b57922143b0f18f3e42":{
      "scriptId":"u71"},
    "6f6cf56b4b6c48cb8038da912ce17c8b":{
      "scriptId":"u72"},
    "f915442532bc4a77a3ec77828e9593d8":{
      "scriptId":"u73"},
    "32d82741d4704e4c830110851a35bf34":{
      "scriptId":"u74"},
    "c1c63ac5720e459d8fafaccf3dc59e98":{
      "scriptId":"u75"}}});