$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1399385438714.97),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"578dc2bf28ad49f9b7b98e831378114e",
    "type":"Axure:Page",
    "name":"About",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dad0879a933f410eaed30f595528982a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1000,
              "height":1000},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"babb7ff5f2744c259d8be51ca3c27b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1000,
                  "height":1000},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u0.png"}},
{
          "id":"0980b58caf2d4635b18195457d98a064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":233,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5023690f4d44dc948fbc0123b11dc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":233,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0015441e9ec4440cb62b43865721cea8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":180},
            "size":{
              "width":660,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c16e745b504824861f592805e4c316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":180},
                "size":{
                  "width":660,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6a14cc05b704990ac4e2451d514cf8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":450},
            "size":{
              "width":140,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b954739d4b4b45ef80e778ae100e597d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":450},
                "size":{
                  "width":140,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u6.png"}},
{
          "id":"06a5b7b293df469b965c38e0b4103fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":450},
            "size":{
              "width":140,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ddda931a2494bdf856382680e7e6074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":450},
                "size":{
                  "width":140,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u6.png"}},
{
          "id":"8d248fd39b5f41ba9025372e16d80706",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":450},
            "size":{
              "width":140,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"916b1ad4b85c4a76bd8894e4022d5407",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":450},
                "size":{
                  "width":140,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u6.png"}},
{
          "id":"0f5fb00338e74b6e951fcc5de6fdf1af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":450},
            "size":{
              "width":140,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691a62d953734edca0d8c947fd1b5313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":450},
                "size":{
                  "width":140,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u6.png"}},
{
          "id":"ff95e4570590446c8a90c58797e54063",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":634},
            "size":{
              "width":760,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u14_line.png"}},
{
          "id":"61f371101e824a3dad9d37eb4ec55e19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":200.5,
              "y":654},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7724ba8eb1f6424c896f886b6a1ee77c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":200.5,
                  "y":654},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7e44046cfc94547b45dbd8948a0a196",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":398.5,
              "y":654},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53801b131412459f9b3268eef6a2b4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":398.5,
                  "y":654},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aafafc0865a14875a44aafe1026411b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":578.5,
              "y":654},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b258d8a72d424778bececcec8727589d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":578.5,
                  "y":654},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a7885e37db64c63a3fba2da1ec204e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":750.5,
              "y":654},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90efd348f94346b19e8f68b9c2815fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":750.5,
                  "y":654},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c70f7eefe70468d9b4bd624c9a17f0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":695},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a6969ed32c9407c9cd9b1ff40d55749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":695},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e42d7f8f59074dd686b838b1b280c22f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":695},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5527064cff4dd0ac1ccbe60677d9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":695},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e18c9d4e3248f3af31387adc1df509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":695},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2ba63c56e74ef5b506f13e948d9602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":695},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed5af81a6cb64723adf45732564bca6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":695},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56712cfdbe194fc290e484ef90ef2106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":695},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dad0879a933f410eaed30f595528982a":{
      "scriptId":"u0"},
    "babb7ff5f2744c259d8be51ca3c27b49":{
      "scriptId":"u1"},
    "0980b58caf2d4635b18195457d98a064":{
      "scriptId":"u2"},
    "7e5023690f4d44dc948fbc0123b11dc4":{
      "scriptId":"u3"},
    "0015441e9ec4440cb62b43865721cea8":{
      "scriptId":"u4"},
    "c6c16e745b504824861f592805e4c316":{
      "scriptId":"u5"},
    "e6a14cc05b704990ac4e2451d514cf8c":{
      "scriptId":"u6"},
    "b954739d4b4b45ef80e778ae100e597d":{
      "scriptId":"u7"},
    "06a5b7b293df469b965c38e0b4103fed":{
      "scriptId":"u8"},
    "9ddda931a2494bdf856382680e7e6074":{
      "scriptId":"u9"},
    "8d248fd39b5f41ba9025372e16d80706":{
      "scriptId":"u10"},
    "916b1ad4b85c4a76bd8894e4022d5407":{
      "scriptId":"u11"},
    "0f5fb00338e74b6e951fcc5de6fdf1af":{
      "scriptId":"u12"},
    "691a62d953734edca0d8c947fd1b5313":{
      "scriptId":"u13"},
    "ff95e4570590446c8a90c58797e54063":{
      "scriptId":"u14"},
    "61f371101e824a3dad9d37eb4ec55e19":{
      "scriptId":"u15"},
    "7724ba8eb1f6424c896f886b6a1ee77c":{
      "scriptId":"u16"},
    "d7e44046cfc94547b45dbd8948a0a196":{
      "scriptId":"u17"},
    "53801b131412459f9b3268eef6a2b4ee":{
      "scriptId":"u18"},
    "aafafc0865a14875a44aafe1026411b9":{
      "scriptId":"u19"},
    "b258d8a72d424778bececcec8727589d":{
      "scriptId":"u20"},
    "8a7885e37db64c63a3fba2da1ec204e5":{
      "scriptId":"u21"},
    "90efd348f94346b19e8f68b9c2815fa3":{
      "scriptId":"u22"},
    "0c70f7eefe70468d9b4bd624c9a17f0b":{
      "scriptId":"u23"},
    "6a6969ed32c9407c9cd9b1ff40d55749":{
      "scriptId":"u24"},
    "e42d7f8f59074dd686b838b1b280c22f":{
      "scriptId":"u25"},
    "8a5527064cff4dd0ac1ccbe60677d9e5":{
      "scriptId":"u26"},
    "c3e18c9d4e3248f3af31387adc1df509":{
      "scriptId":"u27"},
    "6f2ba63c56e74ef5b506f13e948d9602":{
      "scriptId":"u28"},
    "ed5af81a6cb64723adf45732564bca6a":{
      "scriptId":"u29"},
    "56712cfdbe194fc290e484ef90ef2106":{
      "scriptId":"u30"}}});