$axure.loadCurrentPage({
  "url":"join_us.html",
  "generationDate":new Date(1398254197193.33),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"60373e9585ea4dcb93712d85b69f9658",
    "type":"Axure:Page",
    "name":"join us",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b63f3d922744439698ead78d6c5a51c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":620,
              "height":700},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d1170b3334a461e9ee8b0ed3c315c57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":620,
                  "height":700},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/join_us/u0.png"}},
{
          "id":"c5c46cbc008a4bbba20091f8c13ddc80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "location":{
              "x":135,
              "y":70},
            "size":{
              "width":390,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"447083cf7682403d900a70ec30b73b41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "location":{
                  "x":135,
                  "y":70},
                "size":{
                  "width":390,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d87eea9aa42641b5a48abd3de52a2f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":90,
              "y":240},
            "size":{
              "width":490,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ab8d599c634605b122af1037308a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":90,
                  "y":240},
                "size":{
                  "width":490,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbbe4d4b5ad64dbb8d6bdfd7d944fa2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":140,
              "y":454},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d9f22dde91244dc9f03ca884d8ad246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":140,
                  "y":454},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ffe11687bdf412abf3038ff0fedd201",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":454},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"73493ac851614a13b4e6bd0d87c28b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":140,
              "y":500},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49cf489137ac47f0b15dc4e582365abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":140,
                  "y":500},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ae9d96e12154ba69c6cec5f40befb9e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":495},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a716861d186b4b4ba204636d8b249c3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":122,
              "y":578},
            "size":{
              "width":185,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dd198b71ca484796a117a8b02782db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":122,
                  "y":578},
                "size":{
                  "width":185,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c6aa2ff8354fa18872995c1a542fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":75,
              "y":130},
            "size":{
              "width":510,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b6f43f68a674e2caffeed8d7f23727a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":75,
                  "y":130},
                "size":{
                  "width":510,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/join_us/u14.png"}},
{
          "id":"6f7f59e2b00c445f94a6b2cc7d502f02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":99,
              "y":152},
            "size":{
              "width":460,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40f99074d49c467c8b2440a96a21b01f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":99,
                  "y":152},
                "size":{
                  "width":460,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/join_us/u16.png"}},
{
          "id":"54ab59c4cf6e44f48566670acff004e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":75,
              "y":412},
            "size":{
              "width":510,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d920bc45bea4bd2a586ae065c984ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":412},
                "size":{
                  "width":510,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"547a58335bb5428fbacfee0b6ca15a50",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":578},
            "size":{
              "width":140,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"ebf073c8eab7423a89035dc1d8edae5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":200,
              "y":690},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a56f279d6749ac9fa7011716e7f964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":690},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4a7b166534f4d259ba77117253a031e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":75,
              "y":643},
            "size":{
              "width":510,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f075bce34cb64b89844105750d5b5f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":643},
                "size":{
                  "width":510,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b63f3d922744439698ead78d6c5a51c5":{
      "scriptId":"u0"},
    "6d1170b3334a461e9ee8b0ed3c315c57":{
      "scriptId":"u1"},
    "c5c46cbc008a4bbba20091f8c13ddc80":{
      "scriptId":"u2"},
    "447083cf7682403d900a70ec30b73b41":{
      "scriptId":"u3"},
    "d87eea9aa42641b5a48abd3de52a2f9f":{
      "scriptId":"u4"},
    "70ab8d599c634605b122af1037308a26":{
      "scriptId":"u5"},
    "fbbe4d4b5ad64dbb8d6bdfd7d944fa2b":{
      "scriptId":"u6"},
    "6d9f22dde91244dc9f03ca884d8ad246":{
      "scriptId":"u7"},
    "9ffe11687bdf412abf3038ff0fedd201":{
      "scriptId":"u8"},
    "73493ac851614a13b4e6bd0d87c28b32":{
      "scriptId":"u9"},
    "49cf489137ac47f0b15dc4e582365abd":{
      "scriptId":"u10"},
    "3ae9d96e12154ba69c6cec5f40befb9e":{
      "scriptId":"u11"},
    "a716861d186b4b4ba204636d8b249c3b":{
      "scriptId":"u12"},
    "05dd198b71ca484796a117a8b02782db":{
      "scriptId":"u13"},
    "f0c6aa2ff8354fa18872995c1a542fa2":{
      "scriptId":"u14"},
    "7b6f43f68a674e2caffeed8d7f23727a":{
      "scriptId":"u15"},
    "6f7f59e2b00c445f94a6b2cc7d502f02":{
      "scriptId":"u16"},
    "40f99074d49c467c8b2440a96a21b01f":{
      "scriptId":"u17"},
    "54ab59c4cf6e44f48566670acff004e2":{
      "scriptId":"u18"},
    "8d920bc45bea4bd2a586ae065c984ec8":{
      "scriptId":"u19"},
    "547a58335bb5428fbacfee0b6ca15a50":{
      "scriptId":"u20"},
    "ebf073c8eab7423a89035dc1d8edae5c":{
      "scriptId":"u21"},
    "d5a56f279d6749ac9fa7011716e7f964":{
      "scriptId":"u22"},
    "b4a7b166534f4d259ba77117253a031e":{
      "scriptId":"u23"},
    "f075bce34cb64b89844105750d5b5f4c":{
      "scriptId":"u24"}}});