$axure.loadCurrentPage({
  "url":"check_availablity.html",
  "generationDate":new Date(1399986504826.58),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"efe0b6dcf971446ea4bc9955ebb8e3e7",
    "type":"Axure:Page",
    "name":"Check Availablity",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"15c6c9f466fc4af3a3921b84474b72e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":13},
            "size":{
              "width":390,
              "height":467},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb7bbd30a3e2496782c49de6e7e6f8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":13},
                "size":{
                  "width":390,
                  "height":467},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/check_availablity/u0.png"}},
{
          "id":"424b5d9bc77a4aa6a18ff448b9f694b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":112,
              "y":36},
            "size":{
              "width":160,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"523c17e3e70941e88af8602caed4bf70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":112,
                  "y":36},
                "size":{
                  "width":160,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cf8955b57fb4330b601cac93a55299b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":70},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detail/u118_line.png"}},
{
          "id":"35b6285cb84a468390105a5e4c6f252d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":23},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc57f645f1914a349457d58126973096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":23},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3784cf90619544cfb4c405dd58cd29aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":90},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d2a9ad6d8149c68741fa0f9bc19a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":90},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d6a7af3df8544af93c47b9742f44689",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":67,
              "y":121},
            "size":{
              "width":270,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"04/23/2014"},
{
          "id":"dbc6b35cf4f040419d5583332bbbd93c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":280},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"730b79935e2d419f993369cec8758891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":280},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe64abeb13d4a6d8642a54b6dea1436",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":67,
              "y":315},
            "size":{
              "width":270,
              "height":100}},
          "adaptiveStyles":{
},
          "placeholderText":"Ask here… "},
{
          "id":"62b39533de9446688cefb1bef8cc7ebd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":426},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 面板状态为",
                      "panelsToStates":[]}]}]}},
          "tabbable":true},
{
          "id":"21158be0a23345b9923202ba15ce242e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":67,
              "y":147},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e57a62e24cc49509e5a2d42edc54c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":67,
                  "y":147},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36c94d9fbdcb41af9f7e36ec7b03d1ef",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":200},
            "size":{
              "width":270,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8e1a7fdcea8148c29b52c96c38e32663",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":225},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1977772569054688885bbc925481bf27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":225},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"60db917032e8432f9cfa1f8d62c02e10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":67,
              "y":181},
            "size":{
              "width":69,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"931d9aa5086641c687d365eb607a9298",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":67,
                  "y":181},
                "size":{
                  "width":69,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a39529b9416c458492362d6f2ce0a712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":690},
            "size":{
              "width":390,
              "height":610},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"559314fc221a4a129784c7cbdfc9ea6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":690},
                "size":{
                  "width":390,
                  "height":610},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u114.png"}},
{
          "id":"1a3598ed56b04078b57a8ab08a8de8b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":112,
              "y":713},
            "size":{
              "width":160,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4cbf39b88d54c648e1159663d962a80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":112,
                  "y":713},
                "size":{
                  "width":160,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67ab9b94786745daaa6d841c95cfe6a0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":747},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detail/u118_line.png"}},
{
          "id":"e22758dd81934199aaae281d25a06ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":700},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2534e0910847cca74616c40089703d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":700},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1681fa3025440938ca66b1656166f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":74,
              "y":939},
            "size":{
              "width":260,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8823a3f91c5048a1b4ba8da58f65d1bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":74,
                  "y":939},
                "size":{
                  "width":260,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93699ab2793241af8fcde75498fbc3c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":823},
            "size":{
              "width":94,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380cbd666846412e89ab7945d518629f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":823},
                "size":{
                  "width":94,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u142.png"}},
{
          "id":"4399d85932764239bd9313896dfcc99c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":451},
            "size":{
              "width":10,
              "height":229}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u32_end.png",
            "line~":"images/check_availablity/u32_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "15c6c9f466fc4af3a3921b84474b72e1":{
      "scriptId":"u0"},
    "eb7bbd30a3e2496782c49de6e7e6f8a4":{
      "scriptId":"u1"},
    "424b5d9bc77a4aa6a18ff448b9f694b2":{
      "scriptId":"u2"},
    "523c17e3e70941e88af8602caed4bf70":{
      "scriptId":"u3"},
    "7cf8955b57fb4330b601cac93a55299b":{
      "scriptId":"u4"},
    "35b6285cb84a468390105a5e4c6f252d":{
      "scriptId":"u5"},
    "fc57f645f1914a349457d58126973096":{
      "scriptId":"u6"},
    "3784cf90619544cfb4c405dd58cd29aa":{
      "scriptId":"u7"},
    "b7d2a9ad6d8149c68741fa0f9bc19a04":{
      "scriptId":"u8"},
    "1d6a7af3df8544af93c47b9742f44689":{
      "scriptId":"u9"},
    "dbc6b35cf4f040419d5583332bbbd93c":{
      "scriptId":"u10"},
    "730b79935e2d419f993369cec8758891":{
      "scriptId":"u11"},
    "abe64abeb13d4a6d8642a54b6dea1436":{
      "scriptId":"u12"},
    "62b39533de9446688cefb1bef8cc7ebd":{
      "scriptId":"u13"},
    "21158be0a23345b9923202ba15ce242e":{
      "scriptId":"u14"},
    "1e57a62e24cc49509e5a2d42edc54c19":{
      "scriptId":"u15"},
    "36c94d9fbdcb41af9f7e36ec7b03d1ef":{
      "scriptId":"u16"},
    "8e1a7fdcea8148c29b52c96c38e32663":{
      "scriptId":"u17"},
    "1977772569054688885bbc925481bf27":{
      "scriptId":"u18"},
    "60db917032e8432f9cfa1f8d62c02e10":{
      "scriptId":"u19"},
    "931d9aa5086641c687d365eb607a9298":{
      "scriptId":"u20"},
    "a39529b9416c458492362d6f2ce0a712":{
      "scriptId":"u21"},
    "559314fc221a4a129784c7cbdfc9ea6a":{
      "scriptId":"u22"},
    "1a3598ed56b04078b57a8ab08a8de8b0":{
      "scriptId":"u23"},
    "b4cbf39b88d54c648e1159663d962a80":{
      "scriptId":"u24"},
    "67ab9b94786745daaa6d841c95cfe6a0":{
      "scriptId":"u25"},
    "e22758dd81934199aaae281d25a06ac8":{
      "scriptId":"u26"},
    "0f2534e0910847cca74616c40089703d":{
      "scriptId":"u27"},
    "c1681fa3025440938ca66b1656166f0f":{
      "scriptId":"u28"},
    "8823a3f91c5048a1b4ba8da58f65d1bb":{
      "scriptId":"u29"},
    "93699ab2793241af8fcde75498fbc3c5":{
      "scriptId":"u30"},
    "380cbd666846412e89ab7945d518629f":{
      "scriptId":"u31"},
    "4399d85932764239bd9313896dfcc99c":{
      "scriptId":"u32"}}});