$axure.loadCurrentPage({
  "url":"post.html",
  "generationDate":new Date(1397918773432.54),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"54c0e81470bc475aa258309235047054",
    "type":"Axure:Page",
    "name":"Post",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});