$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1397918773214.5),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"22a0407f2b8b47fcb17a62aad7e5cb96",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"321e832764dc46dd896ad05249426164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "size":{
              "width":1000,
              "height":550},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfaa006e5bbd402a940024ccc08f2011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "size":{
                  "width":1000,
                  "height":550},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"837da42076a144d9bd85127ca7fa0de7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":270,
              "y":260},
            "size":{
              "width":500,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 渐进提示 淡入淡出 300 毫秒",
                      "objectsToFades":[{
                          "objectPath":["5736eb2468ae4e47973eb498d631f4e2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":300,
                              "showType":"none"}}}]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 渐进提示 淡入淡出 300 毫秒",
                      "objectsToFades":[{
                          "objectPath":["5736eb2468ae4e47973eb498d631f4e2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":300,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"tell me your school , I will find new house for you !!"},
{
          "id":"8c34a1c9d66d42efa1ea5820fc1649a9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":270},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"578182018ff046518ddeea2100f0c2f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8BCCAC},
            "location":{
              "x":0,
              "y":550},
            "size":{
              "width":1000,
              "height":550},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f55211fe794ee9952e85edef6757a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8BCCAC},
                "location":{
                  "x":0,
                  "y":550},
                "size":{
                  "width":1000,
                  "height":550},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u4.png"}},
{
          "id":"f74a5a9ac4714ff99cb873a0fe7e53e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":152},
            "size":{
              "width":313,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5324f334b00a40848247ad90fc42b604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":152},
                "size":{
                  "width":313,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e9296c3f96e459fa4ce93f10191df71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahomat Regular', 'Tahomat'",
            "fontSize":"40px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF825C,
              "opacity":1},
            "location":{
              "x":400,
              "y":582},
            "size":{
              "width":231,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975ad90186c944878fc6a346d6d88b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahomat Regular', 'Tahomat'",
                "fontSize":"40px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF825C,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":582},
                "size":{
                  "width":231,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f62e3a8cb294a0ea4da62a356f02ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":640},
            "size":{
              "width":339,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4298f9e9524b42cbadeae17346884d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":640},
                "size":{
                  "width":339,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda723548c0740ada32efa0c2616e123",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":335,
              "y":160},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea739e6240a4bd99a6a852bddada962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":160},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"878e66929e464957aa457865c9db3834",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":315},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1d8804fe1e4b10a3c96dae2ba4c3b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":315},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5736eb2468ae4e47973eb498d631f4e2",
          "label":"渐进提示",
          "type":"listBox",
          "styleType":"listBox",
          "visible":false,
          "style":{
            "location":{
              "x":270,
              "y":305},
            "size":{
              "width":500,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search list",
                      "target":{
                        "targetType":"page",
                        "url":"search_list.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "321e832764dc46dd896ad05249426164":{
      "scriptId":"u0"},
    "dfaa006e5bbd402a940024ccc08f2011":{
      "scriptId":"u1"},
    "837da42076a144d9bd85127ca7fa0de7":{
      "scriptId":"u2"},
    "8c34a1c9d66d42efa1ea5820fc1649a9":{
      "scriptId":"u3"},
    "578182018ff046518ddeea2100f0c2f6":{
      "scriptId":"u4"},
    "85f55211fe794ee9952e85edef6757a4":{
      "scriptId":"u5"},
    "f74a5a9ac4714ff99cb873a0fe7e53e1":{
      "scriptId":"u6"},
    "5324f334b00a40848247ad90fc42b604":{
      "scriptId":"u7"},
    "7e9296c3f96e459fa4ce93f10191df71":{
      "scriptId":"u8"},
    "975ad90186c944878fc6a346d6d88b6c":{
      "scriptId":"u9"},
    "6f62e3a8cb294a0ea4da62a356f02ccd":{
      "scriptId":"u10"},
    "4298f9e9524b42cbadeae17346884d43":{
      "scriptId":"u11"},
    "fda723548c0740ada32efa0c2616e123":{
      "scriptId":"u12"},
    "7ea739e6240a4bd99a6a852bddada962":{
      "scriptId":"u13"},
    "878e66929e464957aa457865c9db3834":{
      "scriptId":"u14"},
    "dd1d8804fe1e4b10a3c96dae2ba4c3b2":{
      "scriptId":"u15"},
    "5736eb2468ae4e47973eb498d631f4e2":{
      "scriptId":"u16"}}});