$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1400676667179.76),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"22a0407f2b8b47fcb17a62aad7e5cb96",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"321e832764dc46dd896ad05249426164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "size":{
              "width":1000,
              "height":550},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfaa006e5bbd402a940024ccc08f2011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "size":{
                  "width":1000,
                  "height":550},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"578182018ff046518ddeea2100f0c2f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8BCCAC},
            "location":{
              "x":0,
              "y":550},
            "size":{
              "width":1000,
              "height":550},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85f55211fe794ee9952e85edef6757a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8BCCAC},
                "location":{
                  "x":0,
                  "y":550},
                "size":{
                  "width":1000,
                  "height":550},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"f74a5a9ac4714ff99cb873a0fe7e53e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":152},
            "size":{
              "width":313,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5324f334b00a40848247ad90fc42b604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":152},
                "size":{
                  "width":313,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e9296c3f96e459fa4ce93f10191df71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahomat Regular', 'Tahomat'",
            "fontSize":"40px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF825C,
              "opacity":1},
            "location":{
              "x":400,
              "y":582},
            "size":{
              "width":231,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975ad90186c944878fc6a346d6d88b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahomat Regular', 'Tahomat'",
                "fontSize":"40px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF825C,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":582},
                "size":{
                  "width":231,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f62e3a8cb294a0ea4da62a356f02ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":640},
            "size":{
              "width":339,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4298f9e9524b42cbadeae17346884d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":640},
                "size":{
                  "width":339,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda723548c0740ada32efa0c2616e123",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":335,
              "y":160},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea739e6240a4bd99a6a852bddada962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":160},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"878e66929e464957aa457865c9db3834",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":315},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1d8804fe1e4b10a3c96dae2ba4c3b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":651,
                  "y":315},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bbc87f65d9c400598c2bc607e839400",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":126.5,
              "y":264}},
          "adaptiveStyles":{
},
          "masterId":"910632d876054e9daba5e1ff1427cf71"},
{
          "id":"ee375a17599b4ad7a1be528e40b3e194",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":800,
              "y":400},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c0194ce7c1445d8d1ca218f2a28151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":800,
                  "y":400},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 new post",
                      "target":{
                        "targetType":"page",
                        "url":"new_post.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u19.png"}},
{
          "id":"f849c799916c42388ac5d2492db35ddd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":145,
              "y":419},
            "size":{
              "width":55,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530ff6d1b94b4ae6a9087c7c6c81cedf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":145,
                  "y":419},
                "size":{
                  "width":55,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 Fast channel",
                      "target":{
                        "targetType":"page",
                        "url":"fast_channel.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u21.png"}},
{
          "id":"4cb6fd6bcb994f1382fc002455e72406",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":490},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580858f729ac4c3e971fe27eab169748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":490},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"6520d7e42912489e863b6e44bbbefaf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":490},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cd00d907b584a209cf68149cd532a3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":490},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u23.png"}},
{
          "id":"25ed522994a14374b788c7b65674c894",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1100},
            "size":{
              "width":1000,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"329afb0f65dc483b878521cdbc1cd0bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1100},
                "size":{
                  "width":1000,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u27.png"}}]}},
  "masters":{
    "910632d876054e9daba5e1ff1427cf71":{
      "packageId":"910632d876054e9daba5e1ff1427cf71",
      "type":"Axure:Master",
      "name":"search",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"90ed9246fe554982af88c3bf9d3428b7",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "stateStyles":{
                "hint":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1}}},
              "size":{
                "width":720,
                "height":45}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onTextChange":{
                "description":"OnTextChange",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 渐进提示 淡入淡出 300 毫秒",
                        "objectsToFades":[{
                            "objectPath":["f60087697af14281a617c88104cf67de"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"fade",
                                "duration":300,
                                "showType":"none"}}}]}]}]},
              "onLostFocus":{
                "description":"OnLostFocus",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 渐进提示 淡入淡出 300 毫秒",
                        "objectsToFades":[{
                            "objectPath":["f60087697af14281a617c88104cf67de"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"fade",
                                "duration":300,
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "placeholderText":"tell me your school , I will find new house for you !!"},
{
            "id":"ee1dc63a43dd419e81f512517205750b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":610,
                "y":10},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"f60087697af14281a617c88104cf67de",
            "label":"渐进提示",
            "type":"listBox",
            "styleType":"listBox",
            "visible":false,
            "style":{
              "location":{
                "x":0,
                "y":45},
              "size":{
                "width":500,
                "height":100},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onFocus":{
                "description":"OnFocus",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 search list",
                        "target":{
                          "targetType":"page",
                          "url":"search_list.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"df85b2b91a494b7ca5b94ef47e1bd92e",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":500,
                "y":13},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "321e832764dc46dd896ad05249426164":{
      "scriptId":"u0"},
    "dfaa006e5bbd402a940024ccc08f2011":{
      "scriptId":"u1"},
    "578182018ff046518ddeea2100f0c2f6":{
      "scriptId":"u2"},
    "85f55211fe794ee9952e85edef6757a4":{
      "scriptId":"u3"},
    "f74a5a9ac4714ff99cb873a0fe7e53e1":{
      "scriptId":"u4"},
    "5324f334b00a40848247ad90fc42b604":{
      "scriptId":"u5"},
    "7e9296c3f96e459fa4ce93f10191df71":{
      "scriptId":"u6"},
    "975ad90186c944878fc6a346d6d88b6c":{
      "scriptId":"u7"},
    "6f62e3a8cb294a0ea4da62a356f02ccd":{
      "scriptId":"u8"},
    "4298f9e9524b42cbadeae17346884d43":{
      "scriptId":"u9"},
    "fda723548c0740ada32efa0c2616e123":{
      "scriptId":"u10"},
    "7ea739e6240a4bd99a6a852bddada962":{
      "scriptId":"u11"},
    "878e66929e464957aa457865c9db3834":{
      "scriptId":"u12"},
    "dd1d8804fe1e4b10a3c96dae2ba4c3b2":{
      "scriptId":"u13"},
    "8bbc87f65d9c400598c2bc607e839400":{
      "scriptId":"u14",
      "90ed9246fe554982af88c3bf9d3428b7":{
        "scriptId":"u15"},
      "ee1dc63a43dd419e81f512517205750b":{
        "scriptId":"u16"},
      "f60087697af14281a617c88104cf67de":{
        "scriptId":"u17"},
      "df85b2b91a494b7ca5b94ef47e1bd92e":{
        "scriptId":"u18"}},
    "ee375a17599b4ad7a1be528e40b3e194":{
      "scriptId":"u19"},
    "f8c0194ce7c1445d8d1ca218f2a28151":{
      "scriptId":"u20"},
    "f849c799916c42388ac5d2492db35ddd":{
      "scriptId":"u21"},
    "530ff6d1b94b4ae6a9087c7c6c81cedf":{
      "scriptId":"u22"},
    "4cb6fd6bcb994f1382fc002455e72406":{
      "scriptId":"u23"},
    "580858f729ac4c3e971fe27eab169748":{
      "scriptId":"u24"},
    "6520d7e42912489e863b6e44bbbefaf4":{
      "scriptId":"u25"},
    "9cd00d907b584a209cf68149cd532a3c":{
      "scriptId":"u26"},
    "25ed522994a14374b788c7b65674c894":{
      "scriptId":"u27"},
    "329afb0f65dc483b878521cdbc1cd0bf":{
      "scriptId":"u28"}}});