$axure.loadCurrentPage({
  "url":"search_list.html",
  "generationDate":new Date(1399126228638.88),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"0ea5bfe848784c08808d16c0f525f1a8",
    "type":"Axure:Page",
    "name":"search list",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"21e071f7c5f742668841bf72d0c1e62d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":330,
              "y":13},
            "size":{
              "width":400,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "placeholderText":"tell me your school , I will find new house for you !!"},
{
          "id":"ad4161e039904ad78f5e1932f5092b28",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":688,
              "y":13},
            "size":{
              "width":92,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e28f936a659c4691bda01948758bb8c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Normal', 'Tahoma'",
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":870,
              "height":604},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98afdb7982a64c83a948f254240cc906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Normal', 'Tahoma'",
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":870,
                  "height":604},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_list/u2.png"}},
{
          "id":"06795b53b7a645689ab379b943e99b95",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Tahomat Regular', 'Tahomat'",
            "fontSize":"20px",
            "location":{
              "x":243,
              "y":13},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a89f035866b44f2b2c378843772cc89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahomat Regular', 'Tahomat'",
                "fontSize":"20px",
                "location":{
                  "x":243,
                  "y":13},
                "size":{
                  "width":76,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63c6da68df314c1b89f77a562308f49b",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":275,
              "height":564}},
          "adaptiveStyles":{
}},
{
          "id":"40ae749b8268476286317f04a53f0d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":260,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a5d8d2b215a4900a97be279d27cce1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":260,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_list/u7.png"}},
{
          "id":"1ff9e22783744bb5aa200a9bb253458a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xB2FFFFFF},
            "location":{
              "x":300,
              "y":70},
            "size":{
              "width":640,
              "height":70},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xCC797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26cbb3fce04f4c6c9b5730b8b79730a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xB2FFFFFF},
                "location":{
                  "x":300,
                  "y":70},
                "size":{
                  "width":640,
                  "height":70},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xCC797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_list/u9.png"}},
{
          "id":"c4206a31fdd242bea0b81fdb8bd7a917",
          "label":"切换",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0e5fa80a52464b53a7aef32874145b84",
              "label":"1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"14f7890addc44745a5bb3aa210aa5eb8",
                  "label":"",
                  "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b892c66ee964429f8df4fbb4b1b91246",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 切换 to 2",
                              "panelsToStates":[{
                                  "panelPath":["c4206a31fdd242bea0b81fdb8bd7a917"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd6efaf8ec794e2abde808783184f34d",
                  "label":"",
                  "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":1},
                    "size":{
                      "width":10,
                      "height":12}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc4c955040254449a6b4e804d8eb36a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":1},
                        "size":{
                          "width":10,
                          "height":12}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u14.png"}}]},
{
              "id":"3f577415512e4118b8cb916d97b9def7",
              "label":"2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eb48da9010ca4cfe8883f1d372ed4d0d",
                  "label":"",
                  "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f691cddfc2bb4748ade9ff2b05c1be54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 切换 to 1",
                              "panelsToStates":[{
                                  "panelPath":["c4206a31fdd242bea0b81fdb8bd7a917"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f278bc934504a74a173c24399eb6560",
                  "label":"",
                  "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":2},
                    "size":{
                      "width":12,
                      "height":11}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36055d0dc2d44644ab25c9984c4d1671",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c4206a31fdd242bea0b81fdb8bd7a917",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":2},
                        "size":{
                          "width":12,
                          "height":11}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u18.png"}}]}]},
{
          "id":"8782e1a2ecbd434e89f4c63d40c798f2",
          "label":"切换",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e885b0c1e4984ecc992a64ac877a69c1",
              "label":"1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4adf18f191a463b86ddbb654062c8b3",
                  "label":"",
                  "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":52,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a6591070c944d2a9596d906465845f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":52,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 切换 to 2",
                              "panelsToStates":[{
                                  "panelPath":["8782e1a2ecbd434e89f4c63d40c798f2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"533e46f040044395a80d739766f83bd6",
                  "label":"",
                  "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":1},
                    "size":{
                      "width":10,
                      "height":12}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f0b0d75e47704fd5b1915c54446c5cf8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":1},
                        "size":{
                          "width":10,
                          "height":12}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u14.png"}}]},
{
              "id":"ca009c5a5f2c4324830cdf5acaa2b4c8",
              "label":"2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"916850e952dc4635a0e627be30e676d4",
                  "label":"",
                  "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":52,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1ab5de92e3b425eaa96f37da847c88e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":52,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 切换 to 1",
                              "panelsToStates":[{
                                  "panelPath":["8782e1a2ecbd434e89f4c63d40c798f2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c748406e93354b5da4d8571de66669c5",
                  "label":"",
                  "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":2},
                    "size":{
                      "width":12,
                      "height":11}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef9c0dd04d384f7dbf80bc80f0e6648d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8782e1a2ecbd434e89f4c63d40c798f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":2},
                        "size":{
                          "width":12,
                          "height":11}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u18.png"}}]}]},
{
          "id":"22cfbdfd91164dcf974e531dd63a167e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x4C000000,
              "opacity":0.298039227724075},
            "location":{
              "x":898,
              "y":75},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba9b8b752aa4fe4bb74547fae97a642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x4C000000,
                  "opacity":0.298039227724075},
                "location":{
                  "x":898,
                  "y":75},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d84cd69b5d049768bf820c1bd29b2ec",
          "label":"shanxuan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":64},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ccebd827c2e8432a91e21ad23a6c4869",
              "label":"1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5bff354653f74004a9dec19854496bb7",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":35},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daae4ab34a044f918e81e597180e4ea0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":50,
                          "height":35},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u32.png"}},
{
                  "id":"6cda01968f3140459091181fe316fedd",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":8},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4609fde725c346cd9231e903ffd92234",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":8},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a7d68c82e1414152924c59c568bd467b",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 shanxuan to 2",
                              "panelsToStates":[{
                                  "panelPath":["8d84cd69b5d049768bf820c1bd29b2ec"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 筛选面板 向下滑动 300 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["359c9e9f90dd42d0aa4a79c81c38621e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"9b20aad7724c462c8cd2f6ec93a7b63f",
              "label":"2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"099f9407ad5a48c48bd7fa7ea81d5f43",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF7FD1A9},
                    "size":{
                      "width":50,
                      "height":35},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afafd41189134f389b11fb1bbfeffbd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF7FD1A9},
                        "size":{
                          "width":50,
                          "height":35},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u37.png"}},
{
                  "id":"1292cd9e47704f2caa5c30ee868754e1",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":8},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d76d7f1a98714b8eb3be2ff27fa328b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":8},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f487509db58c42abad51669b34427a61",
                  "label":"",
                  "parentDynamicPanel":"8d84cd69b5d049768bf820c1bd29b2ec",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":50,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 shanxuan to 1",
                              "panelsToStates":[{
                                  "panelPath":["8d84cd69b5d049768bf820c1bd29b2ec"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 筛选面板 向上滑动 300 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["359c9e9f90dd42d0aa4a79c81c38621e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"d1f5b1e9ef5048b5bf0cf5fbbc728f91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":10,
              "height":653},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee0fa4ed0494438b18ba80eaea5a639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":10,
                  "height":653},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_list/u42.png"}},
{
          "id":"f92c50b2ed1d402fbc8e65a253c5a995",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0x0},
{
                  "color":0x0},
{
                  "color":0x33000000},
{
                  "color":0x33000000}]},
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ecfbcc51324b119ab49dca42c194c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0x0},
{
                      "color":0x0},
{
                      "color":0x33000000},
{
                      "color":0x33000000}]},
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":250,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_list/u44.png"}},
{
          "id":"359c9e9f90dd42d0aa4a79c81c38621e",
          "label":"筛选面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":true,
          "diagrams":[{
              "id":"abc165ea90444ae7b2c8d0dc716d2a62",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bbad97acc258422385eecaa9020bef13",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":320},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39547b8b79f94b738146e420afdff637",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":320},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/search_list/u47.png"}},
{
                  "id":"876afb37c0c8434987a58af5714e1fd2",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":51.5},
                    "size":{
                      "width":40,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"46664b67abfc4ef08f5d06668a8da254",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":-17,
                      "y":19},
                    "size":{
                      "width":116,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6dbffd2b9e1146c69898ffdc1b2419ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":-17,
                          "y":19},
                        "size":{
                          "width":116,
                          "height":171}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1b468556825a44d69cbc509b9a45386a",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":155,
                      "y":58.5},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/search_list/u52_line.png"}},
{
                  "id":"2ff6b798385e43e7a335a7433bf8fadf",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":51.5},
                    "size":{
                      "width":40,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4dae11d25a4c45ba89d3c95959256e8c",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":96.5},
                    "size":{
                      "width":110,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"ed2173b9673448bf9d15b9f87bb5b4d8",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":140.5},
                    "size":{
                      "width":110,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"8677a543fc0b43fbb020e0c1d0f7c1fa",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":210},
                    "size":{
                      "width":170,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2412314b9121415380684802635840bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":210},
                        "size":{
                          "width":170,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"3faffc5312d04df2b5b3e117e2c50b33",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":41,
                      "y":270},
                    "size":{
                      "width":59,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"dcb438038cee4478afcca0704429a531",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":270},
                    "size":{
                      "width":59,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 筛选面板 向上滑动 300 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["359c9e9f90dd42d0aa4a79c81c38621e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":300,
                                      "showType":"none"}}}]},
{
                              "action":"linkFrame",
                              "description":"打开 list1 在 (内部框架)",
                              "linkType":"frame",
                              "framesToTargets":[{
                                  "framePath":["63c6da68df314c1b89f77a562308f49b"],
                                  "target":{
                                    "targetType":"page",
                                    "url":"list1.html",
                                    "includeVariables":true}}]}]}]}},
                  "tabbable":true},
{
                  "id":"d8769564d24c45de92c0557e9e391127",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":240},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE1E1E1}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/search_list/u60_line.png"}},
{
                  "id":"eb850e64ba67421ea2550fa486f8ed8b",
                  "label":"",
                  "parentDynamicPanel":"359c9e9f90dd42d0aa4a79c81c38621e",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":17},
                    "size":{
                      "width":110,
                      "height":22}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "21e071f7c5f742668841bf72d0c1e62d":{
      "scriptId":"u0"},
    "ad4161e039904ad78f5e1932f5092b28":{
      "scriptId":"u1"},
    "e28f936a659c4691bda01948758bb8c1":{
      "scriptId":"u2"},
    "98afdb7982a64c83a948f254240cc906":{
      "scriptId":"u3"},
    "06795b53b7a645689ab379b943e99b95":{
      "scriptId":"u4"},
    "5a89f035866b44f2b2c378843772cc89":{
      "scriptId":"u5"},
    "63c6da68df314c1b89f77a562308f49b":{
      "scriptId":"u6"},
    "40ae749b8268476286317f04a53f0d1a":{
      "scriptId":"u7"},
    "7a5d8d2b215a4900a97be279d27cce1c":{
      "scriptId":"u8"},
    "1ff9e22783744bb5aa200a9bb253458a":{
      "scriptId":"u9"},
    "26cbb3fce04f4c6c9b5730b8b79730a0":{
      "scriptId":"u10"},
    "c4206a31fdd242bea0b81fdb8bd7a917":{
      "scriptId":"u11"},
    "14f7890addc44745a5bb3aa210aa5eb8":{
      "scriptId":"u12"},
    "b892c66ee964429f8df4fbb4b1b91246":{
      "scriptId":"u13"},
    "bd6efaf8ec794e2abde808783184f34d":{
      "scriptId":"u14"},
    "bc4c955040254449a6b4e804d8eb36a9":{
      "scriptId":"u15"},
    "eb48da9010ca4cfe8883f1d372ed4d0d":{
      "scriptId":"u16"},
    "f691cddfc2bb4748ade9ff2b05c1be54":{
      "scriptId":"u17"},
    "3f278bc934504a74a173c24399eb6560":{
      "scriptId":"u18"},
    "36055d0dc2d44644ab25c9984c4d1671":{
      "scriptId":"u19"},
    "8782e1a2ecbd434e89f4c63d40c798f2":{
      "scriptId":"u20"},
    "d4adf18f191a463b86ddbb654062c8b3":{
      "scriptId":"u21"},
    "7a6591070c944d2a9596d906465845f2":{
      "scriptId":"u22"},
    "533e46f040044395a80d739766f83bd6":{
      "scriptId":"u23"},
    "f0b0d75e47704fd5b1915c54446c5cf8":{
      "scriptId":"u24"},
    "916850e952dc4635a0e627be30e676d4":{
      "scriptId":"u25"},
    "a1ab5de92e3b425eaa96f37da847c88e":{
      "scriptId":"u26"},
    "c748406e93354b5da4d8571de66669c5":{
      "scriptId":"u27"},
    "ef9c0dd04d384f7dbf80bc80f0e6648d":{
      "scriptId":"u28"},
    "22cfbdfd91164dcf974e531dd63a167e":{
      "scriptId":"u29"},
    "1ba9b8b752aa4fe4bb74547fae97a642":{
      "scriptId":"u30"},
    "8d84cd69b5d049768bf820c1bd29b2ec":{
      "scriptId":"u31"},
    "5bff354653f74004a9dec19854496bb7":{
      "scriptId":"u32"},
    "daae4ab34a044f918e81e597180e4ea0":{
      "scriptId":"u33"},
    "6cda01968f3140459091181fe316fedd":{
      "scriptId":"u34"},
    "4609fde725c346cd9231e903ffd92234":{
      "scriptId":"u35"},
    "a7d68c82e1414152924c59c568bd467b":{
      "scriptId":"u36"},
    "099f9407ad5a48c48bd7fa7ea81d5f43":{
      "scriptId":"u37"},
    "afafd41189134f389b11fb1bbfeffbd2":{
      "scriptId":"u38"},
    "1292cd9e47704f2caa5c30ee868754e1":{
      "scriptId":"u39"},
    "d76d7f1a98714b8eb3be2ff27fa328b0":{
      "scriptId":"u40"},
    "f487509db58c42abad51669b34427a61":{
      "scriptId":"u41"},
    "d1f5b1e9ef5048b5bf0cf5fbbc728f91":{
      "scriptId":"u42"},
    "4ee0fa4ed0494438b18ba80eaea5a639":{
      "scriptId":"u43"},
    "f92c50b2ed1d402fbc8e65a253c5a995":{
      "scriptId":"u44"},
    "a8ecfbcc51324b119ab49dca42c194c4":{
      "scriptId":"u45"},
    "359c9e9f90dd42d0aa4a79c81c38621e":{
      "scriptId":"u46"},
    "bbad97acc258422385eecaa9020bef13":{
      "scriptId":"u47"},
    "39547b8b79f94b738146e420afdff637":{
      "scriptId":"u48"},
    "876afb37c0c8434987a58af5714e1fd2":{
      "scriptId":"u49"},
    "46664b67abfc4ef08f5d06668a8da254":{
      "scriptId":"u50"},
    "6dbffd2b9e1146c69898ffdc1b2419ec":{
      "scriptId":"u51"},
    "1b468556825a44d69cbc509b9a45386a":{
      "scriptId":"u52"},
    "2ff6b798385e43e7a335a7433bf8fadf":{
      "scriptId":"u53"},
    "4dae11d25a4c45ba89d3c95959256e8c":{
      "scriptId":"u54"},
    "ed2173b9673448bf9d15b9f87bb5b4d8":{
      "scriptId":"u55"},
    "8677a543fc0b43fbb020e0c1d0f7c1fa":{
      "scriptId":"u56"},
    "2412314b9121415380684802635840bc":{
      "scriptId":"u57"},
    "3faffc5312d04df2b5b3e117e2c50b33":{
      "scriptId":"u58"},
    "dcb438038cee4478afcca0704429a531":{
      "scriptId":"u59"},
    "d8769564d24c45de92c0557e9e391127":{
      "scriptId":"u60"},
    "eb850e64ba67421ea2550fa486f8ed8b":{
      "scriptId":"u61"}}});