$axure.loadCurrentPage({
  "url":"sign_up.html",
  "generationDate":new Date(1399385437731.87),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"3f9d7fd0eaf6431eb23c7acd217189c2",
    "type":"Axure:Page",
    "name":"sign up",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"225ff436ce6d49bd8e417f61cfd1824a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":181},
            "size":{
              "width":420,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80caf3b8e314124bb689b0540c4dca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":181},
                "size":{
                  "width":420,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u0.png"}},
{
          "id":"20bf07733b8f4ff9912a208893e83000",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":130,
              "y":282},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入您的邮箱"},
{
          "id":"f5763891c35a4d788ab09a2c2493556a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":232,
              "y":205},
            "size":{
              "width":74,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee94ec69aa164903a1012d5371e56741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":232,
                  "y":205},
                "size":{
                  "width":74,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b216066a5084a0c976418ddc896db2f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":282},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"47759d1fb28c4c938d76f0676cef751a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":182,
              "y":355},
            "size":{
              "width":175,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff5cbf15ae86410bbec60b6c389472b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":182,
                  "y":355},
                "size":{
                  "width":175,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a7f949813f742f1aee234f4b2bb8d8b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":286},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/sign_up/u8_line.png"}},
{
          "id":"6a1afbd20e084cac9f903a72902e55f6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":371},
            "size":{
              "width":10,
              "height":120}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u49_end.png",
            "line~":"images/sign_up/u9_line.png"}},
{
          "id":"3a89db41b90f4af983cbd1b19ef126a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":501},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebfd035ca9804f2aa35e5b7612d74942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":501},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b38826d58164444beb0bb1a027630b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":149},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"7a84a57ccf034e689ecec46093b5d8a4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":154},
            "size":{
              "width":10,
              "height":296}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/sign_up/u13_line.png"}},
{
          "id":"10fd64e04097476d8ef8806fc800f3d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":54},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5b35caf10e4619a59014963dc433ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":54},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db84598903b64f67882128ec9c7bfd12",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":444},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"f2d790f33899454bbbf910250cf82454",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1120.00012207031,
              "y":350},
            "size":{
              "width":420,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"513208d2618d496ab44b1a51b8cf69fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120.00012207031,
                  "y":350},
                "size":{
                  "width":420,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u17.png"}},
{
          "id":"df05c96741f9493aabc508c6dc275266",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":1190.00012207031,
              "y":462},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入用户名"},
{
          "id":"87a0c5ea550d4e4f8af68b8b9f9fb2ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1297.00012207031,
              "y":379},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd83946e70d347b5ad7dd24e78abab2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1297.00012207031,
                  "y":379},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e84b80643184dd4ae440ca6766eb22a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1400.00012207031,
              "y":462},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a2036dcbf99e45a3ad8a7d23d90ba9a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1242,
              "y":544},
            "size":{
              "width":175,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7189d825ca5f43908605476dfb18b042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1242,
                  "y":544},
                "size":{
                  "width":175,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"614fce896ef54452bd75bc3216be1d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":440},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f7583d72a841998f51ce57fc5be276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1190,
                  "y":440},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36dd794a0e944bfcb4170e9979c3ebb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1190,
              "y":507},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d8d825535743dcb518f1e9f5542b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1190,
                  "y":507},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60394055d10b44b7a635b92984ecbc7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":650},
            "size":{
              "width":420,
              "height":245},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c7bdf0341bf4ab2aaf5034b8b53a935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":650},
                "size":{
                  "width":420,
                  "height":245},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u29.png"}},
{
          "id":"f8284863b22c491885b6b0b11176a193",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":130,
              "y":750},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入您的邮箱"},
{
          "id":"af64b803654a4e8facffe7c7eb3a14c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":232,
              "y":680},
            "size":{
              "width":74,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7915f0357abf4c1eaeab5a490d5b2155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":232,
                  "y":680},
                "size":{
                  "width":74,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"584b0a36497e41358f492bfbd599a64c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":750},
            "size":{
              "width":80,
              "height":71}},
          "adaptiveStyles":{
}},
{
          "id":"de6d35a76a8f4c03bc9fd4a657a05099",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":182,
              "y":864},
            "size":{
              "width":175,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"450b1d045ecd4bb0b18ef846ba865f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":182,
                  "y":864},
                "size":{
                  "width":175,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d90dd993a6d4680b833d98d49802f73",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":803},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u37_line.png"}},
{
          "id":"0009c268820a4ea0994c3b47a6d79619",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":890},
            "size":{
              "width":10,
              "height":95}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u49_end.png",
            "line~":"images/new_post/u198_line.png"}},
{
          "id":"97e823e9280749b9a9ef101aca029363",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":995},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df1a82bffbac46cf8b3d2419dcc3fe14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":995},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0747586b82574b17be5c751142d1ea6d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":130,
              "y":796},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"密码"},
{
          "id":"24b75934b23f4b76b9774f2c7b10c949",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0088CC,
              "opacity":1},
            "location":{
              "x":130,
              "y":831},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd635d82075f4b1c84a9129547693290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0088CC,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":831},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db4d425dbdd24d8c8b2f23543d768fba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1479.00012207031,
              "y":471},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"acb22896e6dd44f29ba5da11d968ee75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1608,
              "y":465},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d73e341143407794a4df5746ad181b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1608,
                  "y":465},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b1d8962b5f2472395a54cdcc75da932",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1720.00012207031,
              "y":471},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"67d0e8899b8c4f4db0b3b66b0ef31bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1850.00012207031,
              "y":379},
            "size":{
              "width":420,
              "height":331},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"642bfbe011c44a25bf8457d9a1658c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1850.00012207031,
                  "y":379},
                "size":{
                  "width":420,
                  "height":331},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u48.png"}},
{
          "id":"0b842310de5c48dc9e0a7c70b3073eab",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":1920.00012207031,
              "y":491},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入用户名"},
{
          "id":"fd70cce8b5ae428c86a541b36db30e77",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":2027.00012207031,
              "y":408},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46efecb1eb6446a844f681fd9888536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":2027.00012207031,
                  "y":408},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c0373b3b5294737aac953c77904e150",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1920,
              "y":469},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf462bfd8b445509861bcf1ed8c1cbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1920,
                  "y":469},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5631c0f9befd478fb79ed742bc1c6232",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":1920.00012207031,
              "y":530},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"用户名"},
{
          "id":"521446dd53c64796a2288568266fef80",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":1920.00012207031,
              "y":570},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"密码"},
{
          "id":"fff8522598f74e2da64975a4b33f372d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":1920.00012207031,
              "y":613},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"再次输入密码"},
{
          "id":"7faf3c58635f40f1b3a8f60d91b12849",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":2145,
              "y":613},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92d59b251eca4a7881fcc5b8946d3e00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":665},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"438cb237b6b645d4a81a2857cd226e42",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":670},
            "size":{
              "width":10,
              "height":296}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/sign_up/u13_line.png"}},
{
          "id":"91f9058e26f749e8bee995253d6e8fe1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":960},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"7a7766aa77cf403fbab74dcadb96de0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":664},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4c970c194914d36991b6cb8a4d7bbfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":664},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b662ce65a3c4481db409d781d5921528",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":800},
            "size":{
              "width":152,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e41b6bcec940189cd8c9cf4d398bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":800},
                "size":{
                  "width":152,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9292a8fb52df46e5a61804b0dd49f2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":954},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f6e72686e2409590c2c4de063ce07a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":954},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fc789d1bacc4a94919991b48a69824f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":712,
              "y":960},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}},
{
          "id":"b6836719bf6a41289314a40c7f130ef0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":841,
              "y":954},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031d4cb43e484476a847bbcb5125e8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":841,
                  "y":954},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9529f51ec8794eb89c0857fd9d1c4c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":2453,
              "y":379},
            "size":{
              "width":420,
              "height":331},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e55837d42d48f28ea1025bdba82450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2453,
                  "y":379},
                "size":{
                  "width":420,
                  "height":331},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u48.png"}},
{
          "id":"2bf39c00b072493fb6282ef34556bc1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":2630,
              "y":408},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fadfdb11f6864764b427bfbd1fd4c065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":2630,
                  "y":408},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fd2f747e9cb4b7eb7dd2f69d0bd845d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":2646,
              "y":523},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5377b4aff5dc4ccb96a77f7aa6c15418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":2646,
                  "y":523},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fd4c6909a874878a21c909d74474a57",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":2750,
              "y":640},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"75c3040e75394094ae6e465cbc06e7b0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2277,
              "y":471},
            "size":{
              "width":166,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u78_line.png"}},
{
          "id":"abc0b338990a49c0a9112ed2026edcc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":2646,
              "y":554},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"382cc25122614469b43cd259a5d5692c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2646,
                  "y":554},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03e0aa2a3914446c8ff72bfaa58b2def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2516,
              "y":498},
            "size":{
              "width":94,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f669c46935d4b9397eb426a5f5a0241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2516,
                  "y":498},
                "size":{
                  "width":94,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail/u142.png"}},
{
          "id":"20523ca21bbd4685a59eafa3df21f22b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0088CC,
              "opacity":1},
            "location":{
              "x":2670,
              "y":645},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ed618f9a034ee7b2e3144e304518f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0088CC,
                  "opacity":1},
                "location":{
                  "x":2670,
                  "y":645},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"254f09a67b2d430cb88f1ac679e5ac19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0088CC,
              "opacity":1},
            "location":{
              "x":130,
              "y":317},
            "size":{
              "width":97,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f6878fd61842028a73d4f9e76eb74a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0088CC,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":317},
                "size":{
                  "width":97,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c86e2b0f134e149ff74848431c99a9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":336},
            "size":{
              "width":10,
              "height":302}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u49_end.png",
            "line~":"images/sign_up/u87_line.png"}},
{
          "id":"d09d3e0731a741b8b03233fa1ce91be2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":78},
            "size":{
              "width":420,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c40885b667488bae67e066cfb18e94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":78},
                "size":{
                  "width":420,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u0.png"}},
{
          "id":"b4454ac3ebc54c679dd782585c8bfb54",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":720,
              "y":179},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入您的邮箱"},
{
          "id":"1919f184663b4bb498b36b2234f47e91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":822,
              "y":102},
            "size":{
              "width":74,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8dedc1a21bd46a585451d9ab455a547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":822,
                  "y":102},
                "size":{
                  "width":74,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8a6c8396a0f4ec8928ae7433d3ef01e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":179},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fd4c998b70a44a7a9c44dac5b2bcbd5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":772,
              "y":252},
            "size":{
              "width":175,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed80e05fc0e34a4a8542e7f66ac5b99a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":252},
                "size":{
                  "width":175,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6c8c5c7319942bfa052bd19db2a9c50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":720,
              "y":214},
            "size":{
              "width":124,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71eb29837834440f9c86438880a97e75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":720,
                  "y":214},
                "size":{
                  "width":124,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12bf8a7c58be4c41ae33654ea3c781a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":325},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"027db04fbf8c473c818d01fdffae44e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":325},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"188ece549d69412f9c757ac68cabc45d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":349},
            "size":{
              "width":420,
              "height":231},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b166060a65734618bb290324c9b34993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":349},
                "size":{
                  "width":420,
                  "height":231},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_up/u100.png"}},
{
          "id":"e36542ab38264c8c97c6b5f7732c347b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":720,
              "y":450},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入您的邮箱"},
{
          "id":"8517d9b93be24ebcad11733cd8525aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":822,
              "y":373},
            "size":{
              "width":74,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db738141133a42428596de272f8e27d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":822,
                  "y":373},
                "size":{
                  "width":74,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c187e13a0d3641bd8d432aed068ea84d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":450},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8bd4b28332634b4685a928aa6e9eb9f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":772,
              "y":523},
            "size":{
              "width":175,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feea9c98043c48b4a9ba53af49cfb188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":523},
                "size":{
                  "width":175,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09119662feb34a59967def640ef17649",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":720,
              "y":485},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3685ce8e521a49169d4d25e312d733d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":720,
                  "y":485},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"607c3ffc0c4c4c83a5364e2ec0ed6722",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0088CC,
              "opacity":1},
            "location":{
              "x":281,
              "y":831},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f44c1a1e66448bbdd6c7e95f185ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0088CC,
                  "opacity":1},
                "location":{
                  "x":281,
                  "y":831},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22d4223a3dd34143b33099678c309e5b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1017,
              "y":471},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/check_availablity/u29_end.png",
            "line~":"images/sign_up/u12_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "225ff436ce6d49bd8e417f61cfd1824a":{
      "scriptId":"u0"},
    "a80caf3b8e314124bb689b0540c4dca0":{
      "scriptId":"u1"},
    "20bf07733b8f4ff9912a208893e83000":{
      "scriptId":"u2"},
    "f5763891c35a4d788ab09a2c2493556a":{
      "scriptId":"u3"},
    "ee94ec69aa164903a1012d5371e56741":{
      "scriptId":"u4"},
    "3b216066a5084a0c976418ddc896db2f":{
      "scriptId":"u5"},
    "47759d1fb28c4c938d76f0676cef751a":{
      "scriptId":"u6"},
    "ff5cbf15ae86410bbec60b6c389472b2":{
      "scriptId":"u7"},
    "1a7f949813f742f1aee234f4b2bb8d8b":{
      "scriptId":"u8"},
    "6a1afbd20e084cac9f903a72902e55f6":{
      "scriptId":"u9"},
    "3a89db41b90f4af983cbd1b19ef126a4":{
      "scriptId":"u10"},
    "ebfd035ca9804f2aa35e5b7612d74942":{
      "scriptId":"u11"},
    "2b38826d58164444beb0bb1a027630b1":{
      "scriptId":"u12"},
    "7a84a57ccf034e689ecec46093b5d8a4":{
      "scriptId":"u13"},
    "10fd64e04097476d8ef8806fc800f3d7":{
      "scriptId":"u14"},
    "0f5b35caf10e4619a59014963dc433ef":{
      "scriptId":"u15"},
    "db84598903b64f67882128ec9c7bfd12":{
      "scriptId":"u16"},
    "f2d790f33899454bbbf910250cf82454":{
      "scriptId":"u17"},
    "513208d2618d496ab44b1a51b8cf69fd":{
      "scriptId":"u18"},
    "df05c96741f9493aabc508c6dc275266":{
      "scriptId":"u19"},
    "87a0c5ea550d4e4f8af68b8b9f9fb2ce":{
      "scriptId":"u20"},
    "cd83946e70d347b5ad7dd24e78abab2d":{
      "scriptId":"u21"},
    "5e84b80643184dd4ae440ca6766eb22a":{
      "scriptId":"u22"},
    "a2036dcbf99e45a3ad8a7d23d90ba9a8":{
      "scriptId":"u23"},
    "7189d825ca5f43908605476dfb18b042":{
      "scriptId":"u24"},
    "614fce896ef54452bd75bc3216be1d5f":{
      "scriptId":"u25"},
    "24f7583d72a841998f51ce57fc5be276":{
      "scriptId":"u26"},
    "36dd794a0e944bfcb4170e9979c3ebb8":{
      "scriptId":"u27"},
    "30d8d825535743dcb518f1e9f5542b90":{
      "scriptId":"u28"},
    "60394055d10b44b7a635b92984ecbc7b":{
      "scriptId":"u29"},
    "5c7bdf0341bf4ab2aaf5034b8b53a935":{
      "scriptId":"u30"},
    "f8284863b22c491885b6b0b11176a193":{
      "scriptId":"u31"},
    "af64b803654a4e8facffe7c7eb3a14c9":{
      "scriptId":"u32"},
    "7915f0357abf4c1eaeab5a490d5b2155":{
      "scriptId":"u33"},
    "584b0a36497e41358f492bfbd599a64c":{
      "scriptId":"u34"},
    "de6d35a76a8f4c03bc9fd4a657a05099":{
      "scriptId":"u35"},
    "450b1d045ecd4bb0b18ef846ba865f18":{
      "scriptId":"u36"},
    "1d90dd993a6d4680b833d98d49802f73":{
      "scriptId":"u37"},
    "0009c268820a4ea0994c3b47a6d79619":{
      "scriptId":"u38"},
    "97e823e9280749b9a9ef101aca029363":{
      "scriptId":"u39"},
    "df1a82bffbac46cf8b3d2419dcc3fe14":{
      "scriptId":"u40"},
    "0747586b82574b17be5c751142d1ea6d":{
      "scriptId":"u41"},
    "24b75934b23f4b76b9774f2c7b10c949":{
      "scriptId":"u42"},
    "dd635d82075f4b1c84a9129547693290":{
      "scriptId":"u43"},
    "db4d425dbdd24d8c8b2f23543d768fba":{
      "scriptId":"u44"},
    "acb22896e6dd44f29ba5da11d968ee75":{
      "scriptId":"u45"},
    "50d73e341143407794a4df5746ad181b":{
      "scriptId":"u46"},
    "7b1d8962b5f2472395a54cdcc75da932":{
      "scriptId":"u47"},
    "67d0e8899b8c4f4db0b3b66b0ef31bb4":{
      "scriptId":"u48"},
    "642bfbe011c44a25bf8457d9a1658c18":{
      "scriptId":"u49"},
    "0b842310de5c48dc9e0a7c70b3073eab":{
      "scriptId":"u50"},
    "fd70cce8b5ae428c86a541b36db30e77":{
      "scriptId":"u51"},
    "b46efecb1eb6446a844f681fd9888536":{
      "scriptId":"u52"},
    "4c0373b3b5294737aac953c77904e150":{
      "scriptId":"u53"},
    "2cf462bfd8b445509861bcf1ed8c1cbd":{
      "scriptId":"u54"},
    "5631c0f9befd478fb79ed742bc1c6232":{
      "scriptId":"u55"},
    "521446dd53c64796a2288568266fef80":{
      "scriptId":"u56"},
    "fff8522598f74e2da64975a4b33f372d":{
      "scriptId":"u57"},
    "7faf3c58635f40f1b3a8f60d91b12849":{
      "scriptId":"u58"},
    "92d59b251eca4a7881fcc5b8946d3e00":{
      "scriptId":"u59"},
    "438cb237b6b645d4a81a2857cd226e42":{
      "scriptId":"u60"},
    "91f9058e26f749e8bee995253d6e8fe1":{
      "scriptId":"u61"},
    "7a7766aa77cf403fbab74dcadb96de0f":{
      "scriptId":"u62"},
    "e4c970c194914d36991b6cb8a4d7bbfc":{
      "scriptId":"u63"},
    "b662ce65a3c4481db409d781d5921528":{
      "scriptId":"u64"},
    "c8e41b6bcec940189cd8c9cf4d398bac":{
      "scriptId":"u65"},
    "9292a8fb52df46e5a61804b0dd49f2b3":{
      "scriptId":"u66"},
    "f5f6e72686e2409590c2c4de063ce07a":{
      "scriptId":"u67"},
    "5fc789d1bacc4a94919991b48a69824f":{
      "scriptId":"u68"},
    "b6836719bf6a41289314a40c7f130ef0":{
      "scriptId":"u69"},
    "031d4cb43e484476a847bbcb5125e8c1":{
      "scriptId":"u70"},
    "9529f51ec8794eb89c0857fd9d1c4c39":{
      "scriptId":"u71"},
    "98e55837d42d48f28ea1025bdba82450":{
      "scriptId":"u72"},
    "2bf39c00b072493fb6282ef34556bc1c":{
      "scriptId":"u73"},
    "fadfdb11f6864764b427bfbd1fd4c065":{
      "scriptId":"u74"},
    "4fd2f747e9cb4b7eb7dd2f69d0bd845d":{
      "scriptId":"u75"},
    "5377b4aff5dc4ccb96a77f7aa6c15418":{
      "scriptId":"u76"},
    "3fd4c6909a874878a21c909d74474a57":{
      "scriptId":"u77"},
    "75c3040e75394094ae6e465cbc06e7b0":{
      "scriptId":"u78"},
    "abc0b338990a49c0a9112ed2026edcc7":{
      "scriptId":"u79"},
    "382cc25122614469b43cd259a5d5692c":{
      "scriptId":"u80"},
    "03e0aa2a3914446c8ff72bfaa58b2def":{
      "scriptId":"u81"},
    "7f669c46935d4b9397eb426a5f5a0241":{
      "scriptId":"u82"},
    "20523ca21bbd4685a59eafa3df21f22b":{
      "scriptId":"u83"},
    "30ed618f9a034ee7b2e3144e304518f1":{
      "scriptId":"u84"},
    "254f09a67b2d430cb88f1ac679e5ac19":{
      "scriptId":"u85"},
    "48f6878fd61842028a73d4f9e76eb74a":{
      "scriptId":"u86"},
    "d8c86e2b0f134e149ff74848431c99a9":{
      "scriptId":"u87"},
    "d09d3e0731a741b8b03233fa1ce91be2":{
      "scriptId":"u88"},
    "69c40885b667488bae67e066cfb18e94":{
      "scriptId":"u89"},
    "b4454ac3ebc54c679dd782585c8bfb54":{
      "scriptId":"u90"},
    "1919f184663b4bb498b36b2234f47e91":{
      "scriptId":"u91"},
    "f8dedc1a21bd46a585451d9ab455a547":{
      "scriptId":"u92"},
    "e8a6c8396a0f4ec8928ae7433d3ef01e":{
      "scriptId":"u93"},
    "fd4c998b70a44a7a9c44dac5b2bcbd5e":{
      "scriptId":"u94"},
    "ed80e05fc0e34a4a8542e7f66ac5b99a":{
      "scriptId":"u95"},
    "d6c8c5c7319942bfa052bd19db2a9c50":{
      "scriptId":"u96"},
    "71eb29837834440f9c86438880a97e75":{
      "scriptId":"u97"},
    "12bf8a7c58be4c41ae33654ea3c781a1":{
      "scriptId":"u98"},
    "027db04fbf8c473c818d01fdffae44e8":{
      "scriptId":"u99"},
    "188ece549d69412f9c757ac68cabc45d":{
      "scriptId":"u100"},
    "b166060a65734618bb290324c9b34993":{
      "scriptId":"u101"},
    "e36542ab38264c8c97c6b5f7732c347b":{
      "scriptId":"u102"},
    "8517d9b93be24ebcad11733cd8525aa8":{
      "scriptId":"u103"},
    "db738141133a42428596de272f8e27d1":{
      "scriptId":"u104"},
    "c187e13a0d3641bd8d432aed068ea84d":{
      "scriptId":"u105"},
    "8bd4b28332634b4685a928aa6e9eb9f2":{
      "scriptId":"u106"},
    "feea9c98043c48b4a9ba53af49cfb188":{
      "scriptId":"u107"},
    "09119662feb34a59967def640ef17649":{
      "scriptId":"u108"},
    "3685ce8e521a49169d4d25e312d733d2":{
      "scriptId":"u109"},
    "607c3ffc0c4c4c83a5364e2ec0ed6722":{
      "scriptId":"u110"},
    "44f44c1a1e66448bbdd6c7e95f185ced":{
      "scriptId":"u111"},
    "22d4223a3dd34143b33099678c309e5b":{
      "scriptId":"u112"}}});