$axure.loadCurrentPage({
  "url":"allservice.html",
  "generationDate":new Date(1400676674015.44),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"f5f678c9aca643f08e71b266779ae28d",
    "type":"Axure:Page",
    "name":"allservice",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4168957fb5744a04a1bc4039bf708e90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1000,
              "height":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b0f26338c949a6b72f91990a19ee10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1000,
                  "height":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/allservice/u0.png"}},
{
          "id":"71ca43833157474997f06f71374dfcc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":33},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb470b6588524df89210f7af14939dfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":33},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3be4f3af24ab41c0a715e4e63c9b5daf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":80},
            "size":{
              "width":910,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/allservice/u4_line.png"}},
{
          "id":"b13cee8ed81d417f9c748e5dcc1f5fc0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":115},
            "size":{
              "width":910,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/allservice/u4_line.png"}},
{
          "id":"bc92007d6a2f405f8f86a81a6b6af9c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":95},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a971b7f48cb24d4c96ca27acd317de87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":95},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccd3d08e3a9946aea259ad2fd1722212",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":95},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239accd34efc42bfb387b43be4a4ff37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":95},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed6ac6fc11584f329fa0493c88ca422b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":95},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b70a81f69441a88a31de44175732c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":95},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25b59bd16ec14ba88e06257cf4c4450e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":745},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"75dd2d02c56e4d57b09a5a8187a1b3d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":210,
              "y":160},
            "size":{
              "width":146,
              "height":396}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e7a704ee7c2471ca8c154f2632619ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":210,
                  "y":160},
                "size":{
                  "width":146,
                  "height":396}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d282cd6ee804f65ba9031f5a445c7c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":166},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"接机时候的称呼"},
{
          "id":"91269cd0b55d4888a08d194700fc791a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":241},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"bf050923b8da4ba198e6377c2b64a9f6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":204},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"e0ed615a21b440e5ac5385360f3681fb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":276},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"56f46b7497494c50b4b02b596c359086",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":311},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"359fca886ce34c9fa28b98754f8cba5e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":386},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"唯一联系方式 请确保填写正确"},
{
          "id":"a116463041cc40efa4c7e87782895ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":397,
              "y":529},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7496adf2464b7a81efca68ffba0e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":397,
                  "y":529},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"bf97b1a538ad4a37be7bd7ec2796cfb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":529},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe359a46a55b456ab49eb26b487e8f47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":529},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"f09c3a19509f4a13b7d9dbe834d62714",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":529},
            "size":{
              "width":30,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe14d6e8445418688ace2c2720ba9e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":529},
                "size":{
                  "width":30,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u16.png"}},
{
          "id":"4ecd6bb2208b484ab37b115ba3d3b785",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":257,
              "y":611},
            "size":{
              "width":400,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937c8626bf3f428b89cb72b5c3d363df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":257,
                  "y":611},
                "size":{
                  "width":400,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/air_s/u22.png"}},
{
          "id":"2730c3617b9345a59fd15c01e2b58c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":277,
              "y":641},
            "size":{
              "width":360,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ac6e27d0caf4ddb8d35a03cda02029a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":277,
                  "y":641},
                "size":{
                  "width":360,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdfea7fd06bb4ee2a0236ac3e3a70d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":397,
              "y":494},
            "size":{
              "width":40,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915a704044264638a8030a9fb1a3d7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":397,
                  "y":494},
                "size":{
                  "width":40,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1673d214880c4e999ffdba7a781cc93d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":346},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"6ab70936985b4267a22e90a42b505429",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":397,
              "y":421},
            "size":{
              "width":200,
              "height":63}},
          "adaptiveStyles":{
},
          "placeholderText":"例子：两个大行李箱，一个包裹"},
{
          "id":"02f92162f673489a8facf147d3e63313",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":397,
              "y":574},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1ee77babe1465cb281e08d4f0a4eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":397,
                  "y":574},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "4168957fb5744a04a1bc4039bf708e90":{
      "scriptId":"u0"},
    "71b0f26338c949a6b72f91990a19ee10":{
      "scriptId":"u1"},
    "71ca43833157474997f06f71374dfcc3":{
      "scriptId":"u2"},
    "eb470b6588524df89210f7af14939dfd":{
      "scriptId":"u3"},
    "3be4f3af24ab41c0a715e4e63c9b5daf":{
      "scriptId":"u4"},
    "b13cee8ed81d417f9c748e5dcc1f5fc0":{
      "scriptId":"u5"},
    "bc92007d6a2f405f8f86a81a6b6af9c6":{
      "scriptId":"u6"},
    "a971b7f48cb24d4c96ca27acd317de87":{
      "scriptId":"u7"},
    "ccd3d08e3a9946aea259ad2fd1722212":{
      "scriptId":"u8"},
    "239accd34efc42bfb387b43be4a4ff37":{
      "scriptId":"u9"},
    "ed6ac6fc11584f329fa0493c88ca422b":{
      "scriptId":"u10"},
    "70b70a81f69441a88a31de44175732c5":{
      "scriptId":"u11"},
    "25b59bd16ec14ba88e06257cf4c4450e":{
      "scriptId":"u12"},
    "75dd2d02c56e4d57b09a5a8187a1b3d0":{
      "scriptId":"u13"},
    "0e7a704ee7c2471ca8c154f2632619ca":{
      "scriptId":"u14"},
    "1d282cd6ee804f65ba9031f5a445c7c1":{
      "scriptId":"u15"},
    "91269cd0b55d4888a08d194700fc791a":{
      "scriptId":"u16"},
    "bf050923b8da4ba198e6377c2b64a9f6":{
      "scriptId":"u17"},
    "e0ed615a21b440e5ac5385360f3681fb":{
      "scriptId":"u18"},
    "56f46b7497494c50b4b02b596c359086":{
      "scriptId":"u19"},
    "359fca886ce34c9fa28b98754f8cba5e":{
      "scriptId":"u20"},
    "a116463041cc40efa4c7e87782895ed8":{
      "scriptId":"u21"},
    "fe7496adf2464b7a81efca68ffba0e00":{
      "scriptId":"u22"},
    "bf97b1a538ad4a37be7bd7ec2796cfb1":{
      "scriptId":"u23"},
    "fe359a46a55b456ab49eb26b487e8f47":{
      "scriptId":"u24"},
    "f09c3a19509f4a13b7d9dbe834d62714":{
      "scriptId":"u25"},
    "efe14d6e8445418688ace2c2720ba9e3":{
      "scriptId":"u26"},
    "4ecd6bb2208b484ab37b115ba3d3b785":{
      "scriptId":"u27"},
    "937c8626bf3f428b89cb72b5c3d363df":{
      "scriptId":"u28"},
    "2730c3617b9345a59fd15c01e2b58c7e":{
      "scriptId":"u29"},
    "7ac6e27d0caf4ddb8d35a03cda02029a":{
      "scriptId":"u30"},
    "cdfea7fd06bb4ee2a0236ac3e3a70d4b":{
      "scriptId":"u31"},
    "915a704044264638a8030a9fb1a3d7f6":{
      "scriptId":"u32"},
    "1673d214880c4e999ffdba7a781cc93d":{
      "scriptId":"u33"},
    "6ab70936985b4267a22e90a42b505429":{
      "scriptId":"u34"},
    "02f92162f673489a8facf147d3e63313":{
      "scriptId":"u35"},
    "3c1ee77babe1465cb281e08d4f0a4eb7":{
      "scriptId":"u36"}}});