$axure.loadCurrentPage({
  "url":"pay.html",
  "generationDate":new Date(1399986507647.86),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"6e02ded25ae64b67bd9b513ae007e607",
    "type":"Axure:Page",
    "name":"pay",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF4F4F4},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"307243a3d5f24a15b194c2b1083f6344",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":800,
              "height":1300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35abfc7b148c4669a7cbf8e0c0c63fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":800,
                  "height":1300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page-sign_up/u0.png"}},
{
          "id":"a3f9a23b31874690bb491abaababc6cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":190},
            "size":{
              "width":713,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039335e6ac6245cd98e8f338b9def8da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":190},
                "size":{
                  "width":713,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u2.png"}},
{
          "id":"551762ee9f7b4e36aef8d514cc3c81ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":344,
              "y":30},
            "size":{
              "width":132,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7804fa1cf8d84e3eb65f05e0bb19fe55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":344,
                  "y":30},
                "size":{
                  "width":132,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d01c5da2e9574f12b76e254d4249a4ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":53.5,
              "y":77},
            "size":{
              "width":713,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/pay/u6_line.png"}},
{
          "id":"e3811a8e608948b19677f3063adaf44b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":54,
              "y":100},
            "size":{
              "width":713,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4604a0d7814496b9f3a30d1330146d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":54,
                  "y":100},
                "size":{
                  "width":713,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u7.png"}},
{
          "id":"25105d08b20d4e3d88ae2463f3140c4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":70,
              "y":116},
            "size":{
              "width":680,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77c2406e8e74896a270af0bd51493e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":116},
                "size":{
                  "width":680,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56d2a391948e4de58073f3b34befa6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":85,
              "y":267},
            "size":{
              "width":150,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28557e03f7344fa0bce3a0ce21c4a5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":267},
                "size":{
                  "width":150,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u11.png"}},
{
          "id":"c668198a26d84d209986975df240a993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":377},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109c5cb38ef24ca19c2828acbdebe11c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":377},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96a4d38d6528417999489399b662e3b5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":220},
            "size":{
              "width":430,
              "height":220}},
          "adaptiveStyles":{
}},
{
          "id":"6bc38f7b327448d2b25791ccd1d03bb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":527},
            "size":{
              "width":713,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295b73064ec54e74aea658f4a0726906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":527},
                "size":{
                  "width":713,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u2.png"}},
{
          "id":"7b8b59cda37c420bb4617ba75b509e93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":85,
              "y":604},
            "size":{
              "width":150,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a192140870544b01ac54bf37179e19bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":604},
                "size":{
                  "width":150,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u11.png"}},
{
          "id":"233f1f28fdae4c7eb64cf1fe43ae2181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":714},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab9e0f431b7484a828569b686a246c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":714},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ece3de606d24cfebfa6b6735bc1129c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":557},
            "size":{
              "width":430,
              "height":220}},
          "adaptiveStyles":{
}},
{
          "id":"bbb5e9738a4e447fab1a1783afd3e072",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":887},
            "size":{
              "width":713,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf0471fdfe341a2bc483aec5499163b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":887},
                "size":{
                  "width":713,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u2.png"}},
{
          "id":"3c278e6ddfd44a069153018e8192f18d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":85,
              "y":964},
            "size":{
              "width":150,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5970c7ac99af4c5ea3eaaa44223dfc71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":964},
                "size":{
                  "width":150,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay/u11.png"}},
{
          "id":"9321bf725d654a3a94de97ae5851d78f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":1074},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703fcbbc38ac484da1c59905fcc216ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":1074},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2214529cf8894f1aa557f34370753cf1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":917},
            "size":{
              "width":430,
              "height":220}},
          "adaptiveStyles":{
}},
{
          "id":"1520182b265744f19e82a0fefad52466",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "lineSpacing":"72px",
            "location":{
              "x":85,
              "y":180},
            "size":{
              "width":200,
              "height":792}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f05332ea26a341818a45a0f546e69ca4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "lineSpacing":"72px",
                "location":{
                  "x":85,
                  "y":180},
                "size":{
                  "width":200,
                  "height":792}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a916cdfaa9a74e2f9eb77e4ceb05b1cf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":1250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "307243a3d5f24a15b194c2b1083f6344":{
      "scriptId":"u0"},
    "35abfc7b148c4669a7cbf8e0c0c63fe7":{
      "scriptId":"u1"},
    "a3f9a23b31874690bb491abaababc6cd":{
      "scriptId":"u2"},
    "039335e6ac6245cd98e8f338b9def8da":{
      "scriptId":"u3"},
    "551762ee9f7b4e36aef8d514cc3c81ed":{
      "scriptId":"u4"},
    "7804fa1cf8d84e3eb65f05e0bb19fe55":{
      "scriptId":"u5"},
    "d01c5da2e9574f12b76e254d4249a4ee":{
      "scriptId":"u6"},
    "e3811a8e608948b19677f3063adaf44b":{
      "scriptId":"u7"},
    "1c4604a0d7814496b9f3a30d1330146d":{
      "scriptId":"u8"},
    "25105d08b20d4e3d88ae2463f3140c4e":{
      "scriptId":"u9"},
    "b77c2406e8e74896a270af0bd51493e6":{
      "scriptId":"u10"},
    "56d2a391948e4de58073f3b34befa6a1":{
      "scriptId":"u11"},
    "28557e03f7344fa0bce3a0ce21c4a5e5":{
      "scriptId":"u12"},
    "c668198a26d84d209986975df240a993":{
      "scriptId":"u13"},
    "109c5cb38ef24ca19c2828acbdebe11c":{
      "scriptId":"u14"},
    "96a4d38d6528417999489399b662e3b5":{
      "scriptId":"u15"},
    "6bc38f7b327448d2b25791ccd1d03bb1":{
      "scriptId":"u16"},
    "295b73064ec54e74aea658f4a0726906":{
      "scriptId":"u17"},
    "7b8b59cda37c420bb4617ba75b509e93":{
      "scriptId":"u18"},
    "a192140870544b01ac54bf37179e19bb":{
      "scriptId":"u19"},
    "233f1f28fdae4c7eb64cf1fe43ae2181":{
      "scriptId":"u20"},
    "2ab9e0f431b7484a828569b686a246c3":{
      "scriptId":"u21"},
    "7ece3de606d24cfebfa6b6735bc1129c":{
      "scriptId":"u22"},
    "bbb5e9738a4e447fab1a1783afd3e072":{
      "scriptId":"u23"},
    "5bf0471fdfe341a2bc483aec5499163b":{
      "scriptId":"u24"},
    "3c278e6ddfd44a069153018e8192f18d":{
      "scriptId":"u25"},
    "5970c7ac99af4c5ea3eaaa44223dfc71":{
      "scriptId":"u26"},
    "9321bf725d654a3a94de97ae5851d78f":{
      "scriptId":"u27"},
    "703fcbbc38ac484da1c59905fcc216ca":{
      "scriptId":"u28"},
    "2214529cf8894f1aa557f34370753cf1":{
      "scriptId":"u29"},
    "1520182b265744f19e82a0fefad52466":{
      "scriptId":"u30"},
    "f05332ea26a341818a45a0f546e69ca4":{
      "scriptId":"u31"},
    "a916cdfaa9a74e2f9eb77e4ceb05b1cf":{
      "scriptId":"u32"}}});