$axure.loadCurrentPage({
  "url":"old.html",
  "generationDate":new Date(1398665214918.69),
  "isCanvasEnabled":false,
  "variables":["shaixuan"],
  "page":{
    "packageId":"0db6564f077049cf9fedda8becb242c3",
    "type":"Axure:Page",
    "name":"old",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});